Repository Infomaniak/android-kMail, pull requests merged in 2022-07, with the labels that each got.

#103 Add SwipeRefreshLayout in Threads list
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/res/layout/fragment_thread_list.xml
Labels: enhancement

#104 Add ripple effect on Threads list cardview
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/res/layout/item_thread.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#105 Fix RealmList serialization issues
  app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: bug

#122 Fix Realm cleaning
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
Labels: bug

#123 Drafts in Realm
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: feature

#124 Update Realm package (from `io.realm` to `io.realm.kotlin`)
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/api/RealmInstantSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/api/RealmListSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/cache/AppSettingsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
  app/src/main/java/com/infomaniak/mail/data/models/AppSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/SignatureEmail.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/data/models/user/UserInfos.kt
  app/src/main/java/com/infomaniak/mail/data/models/user/UserPreferences.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug

#143 NewMessage fab shrink on scroll down and expand on scroll up
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
Labels: enhancement, dependent

#130 Rework Realm
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  build.gradle
  gradle.properties
Labels: enhancement

#133 Bug fixes
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/data/models/user/UserInfos.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SettingAddressAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: bug

#144 Collapse messages in thread + Display drafts
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/res/drawable/ic_bin.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/menu/account_menu.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#145 Add listener on header to expand it on click
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/layout/item_message.xml
Labels: feature

#137 Mark as seen
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#138 Fix Messages' bodies that are re-downloaded each time a Thread is opened
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
Labels: bug

#139 Bump to Android 32
  app/build.gradle
Labels: enhancement

#149 Replace Java ArrayList by Kotlin MutableList
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBooksResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/SignaturesResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/ThreadsResult.kt
  app/src/main/java/com/infomaniak/mail/ui/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SettingAccountAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SettingAddressAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/KMailHttpClient.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
Labels: enhancement

#150 Remove use of GlobalScope
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: bug

#152 Better naming
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
Labels: enhancement

#153 Attachments
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: bug

#156 Rename `arrow` drawables into `chevron` + Add missing headers
  app/src/main/res/drawable-night/ic_logo_infomaniak_mail.xml
  app/src/main/res/drawable/ic_alarm_clock.xml
  app/src/main/res/drawable/ic_archive_folder.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_attachment_inclined.xml
  app/src/main/res/drawable/ic_chevron_down.xml
  app/src/main/res/drawable/ic_chevron_left.xml
  app/src/main/res/drawable/ic_cog.xml
  app/src/main/res/drawable/ic_drawer_download.xml
  app/src/main/res/drawable/ic_drawer_mailbox.xml
  app/src/main/res/drawable/ic_edit_draft.xml
  app/src/main/res/drawable/ic_email_action_reply.xml
  app/src/main/res/drawable/ic_email_action_reply_to_all.xml
  app/src/main/res/drawable/ic_email_action_send.xml
  app/src/main/res/drawable/ic_envelope.xml
  app/src/main/res/drawable/ic_feedbacks.xml
  app/src/main/res/drawable/ic_folder.xml
  app/src/main/res/drawable/ic_folder_star.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_logo_infomaniak_mail.xml
  app/src/main/res/drawable/ic_param_dots.xml
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_pending_messages.xml
  app/src/main/res/drawable/ic_plus_rounded.xml
  app/src/main/res/drawable/ic_promotions.xml
  app/src/main/res/drawable/ic_restore_arrow.xml
  app/src/main/res/drawable/ic_scheduled_messages.xml
  app/src/main/res/drawable/ic_sent_messages.xml
  app/src/main/res/drawable/ic_social_media.xml
  app/src/main/res/drawable/ic_spam.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_setting_account.xml
  app/src/main/res/values/themes.xml
Labels: bug

#157 Multi accounts
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/ContactsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SettingAccountAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/res/layout/fragment_switch_user.xml
  app/src/main/res/layout/item_switch_user_account.xml
  app/src/main/res/layout/item_switch_user_mailbox.xml
  app/src/main/res/menu/account_menu.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#158 Fix never ending refresh of empty Folder
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
Labels: bug

#159 Display Folders' children in MenuDrawer
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FoldersAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/res/layout/item_folder_menu_drawer.xml
Labels: feature

#160 Fix some TODOs
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_switch_user_account.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement

#161 Add Address Books API call
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/ContactsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
Labels: feature

#151 Add Onboarding
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/ui/LoginActivity.kt
  app/src/main/res/drawable-night/ic_onboarding.xml
  app/src/main/res/drawable/ic_onboarding.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v27/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature

#163 WriteMail screen
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FoldersAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/UiContact.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/drawable-night/ic_onboarding.xml
  app/src/main/res/drawable/background_popup.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_editor_bold.xml
  app/src/main/res/drawable/ic_editor_camera.xml
  app/src/main/res/drawable/ic_editor_clock.xml
  app/src/main/res/drawable/ic_editor_italic.xml
  app/src/main/res/drawable/ic_editor_link.xml
  app/src/main/res/drawable/ic_editor_list.xml
  app/src/main/res/drawable/ic_editor_strikethrough.xml
  app/src/main/res/drawable/ic_editor_text_options.xml
  app/src/main/res/drawable/ic_editor_underline.xml
  app/src/main/res/drawable/ic_onboarding.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/chip_contact.xml
  app/src/main/res/layout/chip_hidden_contacts.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/menu/new_message_menu.xml
  app/src/main/res/navigation/new_message_navigation.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#164 Send & save Emails
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/MessagePriority.kt
  app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#165 Update strings
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#168 Refactor Quotas
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt
Labels: enhancement

#173 Move MenuDrawer in MainActivity
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/fragment_thread_list_content.xml
Labels: enhancement

#172 Replace `collectOnce` with `first`
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
Labels: enhancement

#174 Replace Flow in fragments with Livedata
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: enhancement
