Repository Infomaniak/android-kMail, pull requests merged in 2022-11, with the labels that each got.

#317 Rename all `listenTo` into `observe`
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
Labels: optimization, dependent, quick

#318 Regroup lifecycles together
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/BindingViewHolder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: optimization, dependent, quick

#319 Fix Draft auto-appearing when going back to the Threads list
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
Labels: bug, quick

#315 Implement `Reply` & `Reply all`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#322 Clean MainViewModel
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization

#316 Get last Message to execute action
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization, quick

#321 Handle previous Github comments
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization

#320 Update fetch & save/send Draft policies
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#325 Revamp LiveData
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
Labels: optimization

#326 Handle `Reply`, `Reply All` & `Forward` subject prefixes
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
Labels: feature

#334 Fix crash because `currentMailboxObjectId` is null when logging out
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
Labels: bug, quick

#336 Drafts actions worker
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#327 Add prefix (Draft) in thread list
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#333 Add MenuDrawer swap + Manage Account icons + Fix
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/res/drawable/ic_user_setting.xml
  app/src/main/res/drawable/ic_user_swap.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/layout/item_switch_user_mailbox_menu_drawer.xml
Labels: quick

#346 Fix warning orange color in dark mode
  app/src/main/res/values-night/colors.xml
Labels: quick

#351 Fix thread densities illustrations
  app/src/main/res/drawable-night/bg_list_density_compact.xml
  app/src/main/res/drawable-night/bg_list_density_default.xml
  app/src/main/res/drawable-night/bg_list_density_large.xml
  app/src/main/res/drawable/bg_list_density_compact.xml
  app/src/main/res/drawable/bg_list_density_default.xml
  app/src/main/res/drawable/bg_list_density_large.xml
Labels: quick

#335 Use the correct wording for terms e-mail, email, adresse mail
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#331 Keep the `Thread` object in `ThreadViewModel`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#347 Update MenuDrawer with new style
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerDropdownView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/res/drawable/ic_add_circle.xml
  app/src/main/res/drawable/ic_feedback.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#358 Use `single()` when necessary
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: quick

#360 New read/unread style for threads in ThreadList
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#357 Fix `DraftsActions` worker that was creating an empty Realm at 1st boot
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, quick

#363 Fix thread’s displayed recipient in draft folder
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement

#361 Update empty states with new ones
  app/src/main/java/com/infomaniak/mail/ui/main/EmptyStateView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/res/drawable-night/ic_zero_mail.xml
  app/src/main/res/drawable/ic_empty_state_no_mail.xml
  app/src/main/res/drawable/ic_zero_mail.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/view_empty_state.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#350 Update swipe actions colors and logic
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/res/drawable/ic_alarm_clock.xml
  app/src/main/res/drawable/ic_archive_folder.xml
  app/src/main/res/drawable/ic_bin.xml
  app/src/main/res/drawable/ic_drawer_mailbox.xml
  app/src/main/res/drawable/ic_email_action_move.xml
  app/src/main/res/drawable/ic_envelope.xml
  app/src/main/res/drawable/ic_param_dots.xml
  app/src/main/res/drawable/ic_spam.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/swipe_illustration_content.xml
  app/src/main/res/layout/swipe_left_illustration.xml
  app/src/main/res/layout/swipe_right_illustration.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#359 New message style with cards inside of a thread
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/drawable/mail_divider.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/fragment_thread_list_density_setting.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#362 Upload attachments
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/UploadAttachmentsWorker.kt
Labels: feature

#365 Fix small details
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/res/layout/view_empty_state.xml
Labels: quick

#341 Use new Messages API routes
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesByUidsResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesUidsDeltaResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesUidsResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
Labels: feature

#343 Put back the `Unread` filter
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/HeaderItemDecoration.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: feature, dependent

#352 Add `getCurrentMailbox` & `getCurrentMailboxUuid` helpers
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization

#354 Optimize `toggleSeenStatus` realm usage
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: optimization

#355 Rename `api` variables into `remote`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
Labels: optimization, dependent, quick

#364 Remove `Realm?` extensions + Use `TypedRealm` + Replace `=` with `==`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
Labels: optimization

#366 Multiple fixes for lower api versions
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/res/layout/view_avatar.xml
Labels: bug

#367 Fallback on Realm instead of deleting it when API calls fail
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
Labels: bug

#371 Display infomaniak signatures when composing a new mail
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/res/layout/fragment_new_message.xml
Labels: feature

#373 Remove code related to `SignaturePosition` feature while it's not implemented
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
Labels: bug, quick

#374 Fix close button icon color in dark mode for signature
  app/src/main/res/layout/fragment_new_message.xml
Labels: bug, quick

#375 Fix background color for single mail thread in dark mode
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug, quick

#376 Add placeholder when no custom Folder + Fix margin
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#377 Update Bin icon with new one
  app/src/main/res/drawable/ic_bin.xml
Labels: quick

#356 Create Threads with multiple Messages
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesUidsDeltaResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: feature

#369 Notify only previous Folder & selected Folder in `FolderAdapter`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
Labels: optimization, quick

#368 Improve background drafts work
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/UploadAttachmentsWorker.kt
Labels: enhancement

#379 Base network coroutine worker
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/BaseCoroutineWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement, quick

#381 Refacto `unreadCount` display
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerSwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
  app/src/main/res/layout/item_folder_menu_drawer.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/layout/item_switch_user_mailbox_menu_drawer.xml
  app/src/main/res/values/attrs.xml
Labels: optimization

#382 Recompute Thread when deleting Draft
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: bug

#383 Display version number in MenuDrawer
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
Labels: enhancement
