Repository Infomaniak/android-kMail, pull requests merged in 2022-06, with the labels that each got.

#4 Use Realm Kotlin SDK instead of the Java one
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/data/models/AppSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBooks/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/data/models/attachment/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/attachment/AttachmentData.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/signatures/Signature.kt
  app/src/main/java/com/infomaniak/mail/data/models/signatures/SignatureEmail.kt
  app/src/main/java/com/infomaniak/mail/data/models/threads/ThreadMail.kt
  app/src/main/java/com/infomaniak/mail/data/models/user/UserInfos.kt
  app/src/main/java/com/infomaniak/mail/data/models/user/UserPreferences.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmListConverters.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmUtils.kt
  build.gradle
Labels: optimization

#98 Mark messages as seen when parent thread is clicked on
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Seen.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: feature

#106 Clean / refactor code
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/TestRealmViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmListConverters.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#107 Display "No subject" when needed in Threads list & Messages list
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#108 Listen to network status
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#109 Display localized Folder name
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#110 App & No mails icons
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-night/ic_zero_mail.xml
  app/src/main/res/drawable/ic_kmail.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_zero_mail.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/view_no_mail.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: enhancement

#112 Some fixes
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
Labels: bug

#113 Switch AppSettings from Realm to SharedPreferences
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/data/cache/AppSettingsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/cache/SettingsPreferences.kt
  app/src/main/java/com/infomaniak/mail/data/models/AppSettings.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: enhancement

#116 #05: Use `enumValueOfOrNull<T>`
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/user/UserPreferences.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt
Labels: enhancement

#117 Remove SharedPreferences + Handle app restart when current Mailbox is deleted
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/AppSettingsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/cache/SettingsPreferences.kt
  app/src/main/java/com/infomaniak/mail/data/models/AppSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: bug

#25 Use styles
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/res/drawable-night/ic_zero_mail.xml
  app/src/main/res/drawable/divider.xml
  app/src/main/res/drawable/ic_attachment.xml
  app/src/main/res/drawable/ic_attachment_inclined.xml
  app/src/main/res/drawable/ic_burger.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_chevron_left.xml
  app/src/main/res/drawable/ic_chevron_up.xml
  app/src/main/res/drawable/ic_pencil_1.xml
  app/src/main/res/drawable/ic_zero_mail.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_header_thread.xml
  app/src/main/res/layout/item_header_threadlist.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_search_view.xml
  app/src/main/res/layout/item_thread.xml
  app/src/main/res/layout/item_thread_date_separator.xml
  app/src/main/res/layout/item_thread_see_all_button.xml
  app/src/main/res/layout/view_no_mail.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#126 Fix login Activity crash when deleting `windowActionBar`
  app/src/main/AndroidManifest.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v27/themes.xml
  app/src/main/res/values/themes.xml
Labels: bug

#127 Add `collapsingToolbarLayout` to Thread fragment
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/themes.xml
Labels: feature

#128 Add content descriptions + Fix Loco strings
  app/src/main/res/drawable/ic_attachment_inclined.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_header_thread.xml
  app/src/main/res/layout/item_header_threadlist.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_search_view.xml
  app/src/main/res/layout/item_thread.xml
  app/src/main/res/layout/item_thread_date_separator.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: bug

#120 On boarding
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/ui/LoginActivity.kt
  app/src/main/res/drawable-night/ic_onboarding.xml
  app/src/main/res/drawable/ic_onboarding.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values-v27/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature
