Repository Infomaniak/android-kMail, pull requests merged in 2022-09, with the labels that each got.

#234 Small feedbacks fixes
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: enhancement, optimization

#233 Replace Comments in Controllers with Regions
  app/src/main/java/com/infomaniak/mail/data/cache/appSettings/AppSettingsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DuplicateController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
Labels: enhancement, quick

#235 Fix duplication in `ApiRepository.callApi`
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
Labels: optimization, quick

#231 Multiple small UI fixes
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/drawable/divider.xml
  app/src/main/res/drawable/ic_param_dots.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/view_bottom_quick_action_bar.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#236 Refactor Message model
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: optimization, quick

#211 Fix empty Realm at login
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
Labels: bug, quick

#228 Remove duplicated code in `loadCurrentMailbox`
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization, quick

#230 Replace `LiveData.value` with `LiveData.postValue`
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization, quick

#226 Thread density
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/drawable/ic_bullet.xml
  app/src/main/res/layout/bottom_sheet_detailed_contact.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_switch_user_account.xml
  app/src/main/res/layout/view_avatar.xml
  app/src/main/res/values/attrs.xml
Labels: feature

#238 Update project config
  .idea/codeStyles/Project.xml
  app/build.gradle
  build.gradle
  settings.gradle
Labels: optimization, quick

#232 Refactor ViewModel LiveData
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
Labels: optimization

#239 Remove Realm `findLatest`
  app/src/main/java/com/infomaniak/mail/data/cache/appSettings/AppSettingsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DuplicateController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
Labels: optimization

#241 Rename controllers functions
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
Labels: optimization, quick

#242 Add `@Transient` & `@Ignore` in Models when needed
  app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/data/models/user/UserPreferences.kt
  app/src/main/java/com/infomaniak/mail/data/models/user/UserResult.kt
Labels: optimization, quick

#244 Clean Quotas code
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
Labels: optimization, quick

#246 Fix scroll to top
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug, quick

#245 Move `startUpdatedAtJob` to ViewModel
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
Labels: optimization, quick

#243 Fix `markAsSeen` so it updates the Folder's `unreadCount`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement

#248 Swipe Thread as unseen
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: feature

#240 Use Realm queries
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RecipientController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/DateSeparatorItemDecoration.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/item_message.xml
Labels: optimization

#250 Realm DiffUtil
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
Labels: enhancement

#258 Remove deleted Realm Messages from Thread when fetching API
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: enhancement, quick

#253 Remove Controller call in Fragment
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: optimization, quick

#271 Remove SwitchUser `isCollapsed` list and store value in the model
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
Labels: quick

#264 Clean code & layouts
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/values/themes.xml
Labels: optimization, quick

#273 Fix ViewModels usage
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: optimization, quick

#261 Replace ThreadAdapter `DiffUtil` with `OnRealmChanged`
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
Labels: optimization

#265 Add UiSettings with NightMode & ColorTheme
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/data/models/UiSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
Labels: feature

#247 Simplify DB upserts
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DuplicateController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Contact.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
Labels: optimization

#274 Remove duplicated Messages Uids when toggling Seen/Unseen
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization, quick

#260 Embedded objects
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#257 Embedded Quotas
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/QuotasController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
Labels: enhancement

#275 Controllers refactor
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DuplicateController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Duplicate.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: optimization
