Repository Infomaniak/android-kMail, pull requests merged in 2022-12, with the labels that each got.

#386 Fix app version not showing on all devices
  app/src/main/res/layout/fragment_menu_drawer.xml
Labels: bug

#387 Fix download all attachments for subjects < 30 characters
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#385 Sync messages worker
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
  build.gradle
  settings.gradle
Labels: feature

#388 Add `configChanges="orientation|screenSize"` in Manifest for all Activities
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug, quick

#391 Use new delimiter for `references`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: bug

#390 Use production URL for new API routes
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
Labels: enhancement

#392 Remove info screens when adding account while already logged in like iOS
  app/src/main/java/com/infomaniak/mail/ui/login/IntroPagerAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
Labels: enhancement, quick

#394 Trigger drafts view to force refresh when work finished
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#395 Cancel all works when the last user has been logout
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: enhancement

#399 Swipe actions tutorial when first logging in
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: enhancement

#398 Request multiple permissions needed from MainActivity
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
Labels: enhancement

#404 Start sync worker with delayed duration and Avoid launching the work when it is unnecessary
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: enhancement

#401 Deeplink for new message Notification click
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: enhancement

#403 Refacto Thread fragment & viewModel
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#410 Ignore SyncMessagse new message if it has already been seen
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: enhancement

#411 Schedule SyncMessagesWorker on backpressed because it's ignored by stop lifecycle
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: bug

#414 Snack bar correct colors
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#413 New style for selected items in MenuDrawer
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/values/styles.xml
Labels: optimization, quick

#422 Move `getMenuFolders` from MenuDrawer fragment to viewModel
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
Labels: optimization, quick

#408 Refactor MainVM `current` objects
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: optimization

#417 Rework Folder `unreadCount`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerSwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserMailboxesAdapter.kt
Labels: enhancement

#419 Folders rules
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: enhancement

#412 Made whole swipe setting illustration clickable
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSettingsFragment.kt
  app/src/main/res/layout/fragment_swipe_actions_settings.xml
  app/src/main/res/values/attrs.xml
Labels: enhancement

#420 Refacto `read`/`unread` actions on Thread
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
Labels: enhancement

#421 Refacto `delete` action on Thread & Draft in a Thread
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#423 Optimize Threads creation algorithm
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingViewModel.kt
Labels: optimization

#426 Temporary Realm crash fix
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
Labels: bug, quick

#425 Remove unused nullability of some `realm` objects in Controllers
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/QuotasController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
Labels: optimization

#430 Hide "Message display mode" setting
  app/src/main/res/layout/fragment_settings.xml
Labels: optimization, quick

#429 Reset `from` & `to` when recomputing Thread
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: bug, quick

#428 Factorize code to get displayed Message in Threads list
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: optimization, quick

#427 Clean network listener code
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: optimization, quick

#432 Remove HTML from Draft `body`
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug, quick

#433 Fix invalid MergedContact
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
Labels: bug, quick

#434 fix: not redirected to the right email notification when there is many
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug

#436 Make `currentDraftLocalUuid` nullable instead of `lateinit`
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug, quick

#439 Automatically back after choosing a swipe action in settings
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
Labels: enhancement, quick

#438 New profil disconnection route and design
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/res/layout/fragment_manage_mail_address.xml
  app/src/main/res/layout/item_attachment.xml
  app/src/main/res/layout/item_switch_user_account.xml
  app/src/main/res/layout/item_switch_user_mailbox.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#440 `isMe()` is now correctly checking the email with the `currentMailbox`, and not the `currentUser`
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: bug, quick

#435 New message composition
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/MergedContact.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/layout/chip_hidden_contacts.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/item_attachment.xml
  app/src/main/res/layout/view_recipient_field.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#441 Now lists mailboxes in profile
  app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/ManageMailAddressViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SimpleMailboxAdapter.kt
  app/src/main/res/layout/fragment_manage_mail_address.xml
  app/src/main/res/layout/item_mailbox_my_account.xml
Labels: enhancement

#437 Action `favorite` on Thread & Message
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#442 Fix subject field in new message composition not growing when needed
  app/src/main/res/layout/fragment_new_message.xml
Labels: quick
