Repository Infomaniak/android-kMail, pull requests merged in 2022-08, with the labels that each got.

#181 Styling MenuAccount
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/ThemedActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_plus_rounded.xml
  app/src/main/res/layout/fragment_switch_user.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_switch_user_account.xml
  app/src/main/res/layout/item_switch_user_mailbox.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#180 "Unread messages" filter
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailRealm.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/res/drawable/ic_burger.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/item_thread_date_separator.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#187 Add empty line before `return` statements
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/KMailHttpClient.kt
Labels: enhancement

#189 Refactor Realm & ViewModels
  app/src/main/java/com/infomaniak/mail/data/MailData.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/MailApi.kt
  app/src/main/java/com/infomaniak/mail/data/cache/ContactsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxContentController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/MailboxInfoController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/appSettings/AppSettingsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RecipientController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/ThemedActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FoldersAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/MenuDrawerSwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_attachment.xml
  app/src/main/res/layout/item_detailed_contact.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_switch_user_mailbox.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#196 Fix Folder's unread count in Threads list
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt
Labels: bug, quick

#197 Remove `observeOnce` + Use `AccountUtils.getAllUsersSync()` instead of `getAllusers`
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt
Labels: enhancement, quick

#202 Display last Message preview in Threads list
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/ModelsUtils.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, dependent

#203 Uniformize adapters
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/res/layout/fragment_thread.xml
Labels: enhancement, quick

#199 Fix crash when opening Mailbox
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
Labels: bug, dependent

#200 Listen Realm in SwitchUser menu
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserViewModel.kt
Labels: enhancement, quick

#201 Rename ViewModels
  app/src/main/java/com/infomaniak/mail/ui/main/menu/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageFragment.kt
Labels: enhancement, quick

#204 Get Realm flows synchronously when it's useless to get them asynchronously
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newmessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
Labels: enhancement, quick

#205 Handle duplicated Messages + Fix MarkAsSeen
  app/src/main/java/com/infomaniak/mail/data/cache/RealmController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DuplicateController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Duplicate.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
Labels: bug, enhancement

#206 Move a few needed functions in `Correspondent`
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/data/models/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/data/models/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
Labels: enhancement, quick

#207 Add `Bcc` field to the details of sent/received mails
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/res/layout/item_message.xml
Labels: enhancement, quick

#209 Put back ShowLoading timer in Threads list
  app/src/main/java/com/infomaniak/mail/ui/main/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadListFragment.kt
Labels: bug, enhancement

#210 Reorganize packages
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/contact/ContactFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/BindingViewHolder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerSwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/NewFolderDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/UiContact.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionItemView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MainActionsView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAccountsAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
  app/src/main/res/layout/bottom_sheet_detailed_contact.xml
  app/src/main/res/layout/bottom_sheet_reply.xml
  app/src/main/res/layout/dialog_new_folder.xml
  app/src/main/res/layout/fragment_auto_replay_settings.xml
  app/src/main/res/layout/fragment_bottom_sheet_get_more_storage.xml
  app/src/main/res/layout/fragment_bottom_sheet_message_actions.xml
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/fragment_email_address_settings.xml
  app/src/main/res/layout/fragment_manage_mail_address.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_select_settings.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_signature_setting.xml
  app/src/main/res/layout/fragment_spam_settings.xml
  app/src/main/res/layout/fragment_switch_user.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/new_message_navigation.xml
Labels: enhancement

#227 Fix & explain magic number for `offsetTrigger`
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement, quick

#229 Tweak SwipeRefreshLayout
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement, quick
