Repository Infomaniak/android-kMail, pull requests merged in 2022-10, with the labels that each got.

#285 Refactor all `by lazy`
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/AccentColorSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/DisplayModeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ExternalContentSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioButtonView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ThemeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadListDensitySettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/MailboxSettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MainActionsView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/java/com/infomaniak/mail/views/BottomQuickActionBarView.kt
Labels: optimization, quick

#290 Create `correspondent` package
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/UiContact.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: optimization, quick

#282 Small fixes
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Contact.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/HeaderItemDecoration.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/drawable/ic_star_filled.xml
  app/src/main/res/layout/fragment_thread.xml
Labels: bug, optimization, quick

#283 Refactor `LaunchActivity`
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/appSettings/AppSettingsController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfos/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfos/ContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization

#281 Clean ThreadFragment `observers` code
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: optimization

#291 Update `saveDraft` API call return value
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/models/SaveDraftResult.kt
Labels: optimization, quick

#292 Rework `MessagePriority`
  app/src/main/java/com/infomaniak/mail/data/models/Priority.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
Labels: optimization, quick

#304 Create `draft` package
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Priority.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/SaveDraftResult.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization, quick

#302 Fix typo in `MailboxInfo` & `UserInfo`
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/QuotasController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/ContactController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/MailboxSettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: optimization, quick

#295 Rework `DraftAction`
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization, quick

#299 Add `Signature` to Realm
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: feature, quick

#301 Open existing Draft
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#305 Replace SharedFlow with Flow
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/QuotasController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization, quick

#307 Clean NewMessage fragment code
  app/src/main/java/com/infomaniak/mail/data/models/draft/Priority.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization, quick

#306 Force `ThreadMode.MESSAGES` in `Draft` folder
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
Labels: feature

#310 Clean API Routes variables names
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization, quick

#308 Swipe to delete Thread
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/DeleteMessageResult.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: feature

#262 Merge Contacts from IK & phone together + Display Recipients' avatar
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/MergedContact.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/UiContact.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#312 Flatten `RealmDatabase`
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization

#278 Styling `Manage my account`
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SimpleSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioButtonView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioGroupView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/res/anim/fast_out_extra_slow_in.xml
  app/src/main/res/anim/fragment_swipe_enter.xml
  app/src/main/res/anim/fragment_swipe_exit.xml
  app/src/main/res/anim/fragment_swipe_pop_enter.xml
  app/src/main/res/anim/fragment_swipe_pop_exit.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/fragment_accent_color_setting.xml
  app/src/main/res/layout/fragment_cancel_delay_setting.xml
  app/src/main/res/layout/fragment_display_mode_setting.xml
  app/src/main/res/layout/fragment_external_content_setting.xml
  app/src/main/res/layout/fragment_forward_mails_setting.xml
  app/src/main/res/layout/fragment_mailbox_settings.xml
  app/src/main/res/layout/fragment_manage_mail_address.xml
  app/src/main/res/layout/fragment_send_settings.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
  app/src/main/res/layout/fragment_swipe_actions_settings.xml
  app/src/main/res/layout/fragment_switch_user.xml
  app/src/main/res/layout/fragment_theme_setting.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/fragment_thread_list_density_setting.xml
  app/src/main/res/layout/view_simple_setting.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: feature

#279 Easier way of accessing attributes in custom views (factorized)
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SimpleSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioButtonView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioGroupView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionItemView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MainActionsView.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/java/com/infomaniak/mail/views/BottomQuickActionBarView.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
Labels: enhancement

#287 Manage Draft
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Priority.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MainActionsView.kt
Labels: feature

#288 Directly go to NewMessage when opening a Thread that is just 1 Draft
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#300 Add Signature in Draft
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: feature

#314 Refactor Drafts to use `LocalUuid` & `RemoteUuid`
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/SaveDraftResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature
