Repository Infomaniak/android-kMail, pull requests merged in 2023-05, with the labels that each got.

#890 Fix blockquotes display, wrap long lines and refactor + optimize code for future mail processing
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/raw/add_padding.css
  app/src/main/res/raw/custom_style.css
  app/src/main/res/raw/set_margin_around_mail.css
Labels: enhancement

#891 Enables first version of a zoom on emails for the time being
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageBodyScaleListener.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageBodyTouchListener.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
Labels: feature

#900 To execute Action on a Thread, get last Message which is not a Draft & not from Me
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
Labels: enhancement

#901 Fix crash if user did twice the same action
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug

#902 Fallback on 1st Signature if there is no default one
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
Labels: bug

#905 Factorize `return` if action Threads are empty
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization

#907 Filters Contacts to get only those with an email
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
Labels: enhancement

#908 fix: Several notifications are showed
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: bug, enhancement

#911 Fix Messages that are wrongly merged in same Thread
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: bug

#909 Stop the Threads algo when a API call fails
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: bug

#912 Translate some Errors
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ApiErrorException.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/standard/java/com/infomaniak/mail/GplayExtensions.kt
Labels: feature

#913 Catch timeout in Threads algorithm
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
Labels: bug

#884 Attach Mailbox tunnel
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/MailboxLinkedResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/MailboxPermissions.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/res/drawable/ic_password_eye.xml
  app/src/main/res/drawable/ic_show_password.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_attach_mailbox.xml
  app/src/main/res/layout/fragment_move.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#918 Fix `currentMailbox` not selected
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: bug

#914 Add Attachment sentry
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: optimization

#922 Add ThreadsAlgo breadcrumbs
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: optimization

#923 Update Mailbox notification Sentry
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: optimization

#926 Drafts ErrorToast is now correctly displayed
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#928 Dagger hilt: init + worker support
  app/build.gradle
  app/src/fdroid/java/com/infomaniak/mail/GplayExtensions.kt
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/di/ApplicationModule.kt
  app/src/main/java/com/infomaniak/mail/receivers/RebootReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/GplayExtensions.kt
  app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
  build.gradle
  gradle/libs.versions.toml
Labels: enhancement

#933 Ignore notification if no user logged in
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
Labels: feature

#943 Fix fdroid build
  app/src/fdroid/java/com/infomaniak/mail/GplayUtils.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/GplayExtensions.kt
  app/src/standard/java/com/infomaniak/mail/GplayUtils.kt
  app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
Labels: bug

#940 Various code enhancements before `LoadMore` feature
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/SelectedThread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: optimization, quick

#936 Html sanitization for displayed emails
  HtmlCleaner/build.gradle
  HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/BodyCleaner.kt
  HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/HeadCleaner.kt
  HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/HtmlSanitizer.kt
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
  build.gradle
  settings.gradle
Labels: feature

#942 Fix forward attachments
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/res/layout/fragment_new_message.xml
Labels: bug

#938 Toggle light and dark display of mails using js instead of reloading all of the mail
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
Labels: enhancement

#929 At 1st opening of a Folder, fetch 500 Messages by batches of 25
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesUidsDeltaResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/GetMessagesUidsResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: feature

#941 Add "Load more" button
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/res/layout/item_thread_load_more_button.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#949 Fix Attachments with same name
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
Labels: bug

#950 Rename `Infos` into `Info`
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/FirebaseApiRepository.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegistrationInfo.kt
Labels: optimization

#951 Simplify `quotas` usage
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
Labels: optimization

#948 Dagger Hilt dispatchers
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/di/CoroutinesDispatchersModule.kt
  app/src/main/java/com/infomaniak/mail/di/CoroutinesQualifiers.kt
  app/src/main/java/com/infomaniak/mail/receivers/RebootReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
  gradle/libs.versions.toml
Labels: enhancement, feature

#954 Update Signatures Sentry to make it trigger more often
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization, quick

#953 Uniformize & simplify queries to get Maibloxes
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: optimization

#955 Block distant images
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ExternalContentSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageAlertView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/color/ripple_color_blue_mail.xml
  app/src/main/res/drawable/ic_message_alert_distant_images.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/layout_attachments.xml
  app/src/main/res/layout/view_message_alert.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#957 Block images in Spam folder with no regard for the user setting + Default to "Always show images"
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#956 Fix longpress on webview that makes the recyclerview jump on ThreadFragment
  app/src/main/res/layout/item_message.xml
Labels: bug, quick

#959 Add comments to clarify the reason for the focusInTouchMode fix
  app/src/main/res/layout/item_message.xml
Labels: quick

#958 Use `reload()` when changing screen size to rerender emails instead of `loadUrl()`
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#961 Factorize all `refreshThreads` calls into 1 call
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageAlertView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: optimization

#962 Move Threads algorithm to its own RefreshController instead of being in MessageController
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: optimization, quick

#965 Add sentry log for NoSuchElementException
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  gradle/libs.versions.toml
Labels: enhancement

#964 App doesn't crash anymore when refreshing Threads without connectivity
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: bug

#946 Auto hide/show "Load more" button
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: feature

#973 Update settings padding
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioGroupView.kt
  app/src/main/res/layout/fragment_accent_color_setting.xml
  app/src/main/res/layout/fragment_external_content_setting.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_swipe_actions_settings.xml
  app/src/main/res/layout/fragment_theme_setting.xml
  app/src/main/res/layout/fragment_thread_list_density_setting.xml
  app/src/main/res/layout/swipe_left_illustration.xml
  app/src/main/res/layout/swipe_right_illustration.xml
  app/src/main/res/layout/view_item_setting.xml
  app/src/main/res/layout/view_setting_radio_button.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#975 Fix `NoSuchElementException` : List is empty
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  gradle/libs.versions.toml
Labels: bug

#976 Track running Draft
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: feature
