Repository Infomaniak/android-kMail, pull requests merged in 2023-08, with the labels that each got.

#1188 Add dividers in suggested Contacts lists
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/res/layout/fragment_new_message.xml
Labels: feature

#1187 Open field when clicking on chip
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
Labels: feature

#1190 Update chevron to follow the specs
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/view_decorated_text_item.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
Labels: enhancement, quick

#1181 Clean code
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/DecoratedTextItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/IndentableFolder.kt
Labels: optimization, quick

#1191 Fix Folders indent & chevron in MenuDrawer
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerDropdownView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/views/CollapsableItem.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/IndentableFolder.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/MenuDrawerFolderItemView.kt
Labels: bug

#1192 Backup Message heavy data
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: bug

#1200 Fix `Message.isFullyDownloaded`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: bug

#1199 Refactor `Message.initLocalValues()` code
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: optimization, quick

#1195 Centralize navigation to NewMessageActivity
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#1197 Add snackbar debounce timer when sending to avoid flickering
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: enhancement, quick

#1205 Add `loginUtils.initShowError(::showError)` in LoginFragment
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
Labels: bug

#1202 Fix login fragment manager
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
Labels: bug, enhancement

#1210 Check dynamically if name has invalid character
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1208 fix: Search in local with a quote throw RLM_ERR_INVALID_QUERY_STRING
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: bug

#1211 Update `RefreshController.handleAddedUids()` Sentries
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization

#1209 Make RefreshController injectable
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: enhancement

#1215 Improve new message activity
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: enhancement

#1213 Cancel ThreadsAlgo in Search
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: bug

#1216 Fix backstack in `NoMailboxActivity`
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/LoginUtils.kt
Labels: bug

#1221 Uniformize `startActivity` usage
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization

#1220 Rename item view classes and package
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/UnreadItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/DecoratedItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/IndentableFolder.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/InvalidMailboxItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/SelectableFolderItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/SelectableItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/SelectableMailboxItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/SimpleMenuDrawerItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/UnreadFolderItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/UnreadItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/UnreadMailboxItemView.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/item_folder_menu_drawer.xml
  app/src/main/res/layout/item_invalid_mailbox.xml
  app/src/main/res/layout/item_mailbox_menu_drawer.xml
  app/src/main/res/layout/item_search_folder.xml
  app/src/main/res/layout/item_selectable_folder.xml
  app/src/main/res/layout/item_selectable_mailbox.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#1219 Fix Signature API error
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
Labels: bug

#1223 Fix shimmering staying displayed behind mail body after it got fetched
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: bug, quick

#1225 Comment the choice of snackbar behavior for mails that take a long time to send
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: quick

#1224 feat: Improve signature setting logic
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
Labels: enhancement

#1217 If ThreadsAlgo failed because of `message not found`, try again after some delay
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: bug

#1204 Update padding to design system
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioGroupView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/DecoratedItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/InvalidMailboxItemView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/UnreadItemView.kt
  app/src/main/res/drawable/divider.xml
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_mailbox_settings.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_move.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/fragment_send_settings.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_swipe_actions_settings.xml
  app/src/main/res/layout/item_bottom_sheet_action.xml
  app/src/main/res/layout/item_divider_horizontal.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/view_contact_chip_context_menu.xml
  app/src/main/res/layout/view_decorated_text_item.xml
  app/src/main/res/layout/view_main_actions.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/layout/view_message_alert.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#1222 Simplify context access in AndroidViewModels to remove duplication
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: enhancement, quick

#1231 fix: Network exception from RegisterUserDeviceWorker
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
Labels: bug, quick

#1229 Update date display format to be shorter
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: feature

#1238 Correctly sort Mailboxes
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
Labels: bug

#1234 Hilt PlayServices
  app/src/fdroid/java/com/infomaniak/mail/FdroidModule.kt
  app/src/fdroid/java/com/infomaniak/mail/FdroidPlayServicesUtils.kt
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/PlayServicesUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/StandardMainApplication.kt
  app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt
  app/src/standard/java/com/infomaniak/mail/di/StandardModule.kt
  app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
Labels: enhancement

#1242 Reformat code
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/main/res/layout/fragment_move.xml
  app/src/standard/java/com/infomaniak/mail/di/StandardModule.kt
  app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
Labels: enhancement, quick

#1237 Hilt register user device
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/di/ApplicationModule.kt
  app/src/standard/java/com/infomaniak/mail/StandardMainApplication.kt
  app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt
  app/src/standard/java/com/infomaniak/mail/di/StandardEntryPoint.kt
  app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
Labels: enhancement

#1245 fix: Inconsistency in adapter with RealmChangesBinding
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
Labels: bug, enhancement

#1235 Cannot SPAM from a Message
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-fr/strings.xml
Labels: enhancement

#1233 Optimize Threads algo
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization

#1246 Remove `SelectedThread`
  app/src/main/java/com/infomaniak/mail/data/models/thread/SelectedThread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
Labels: optimization

#1247 Update wording for settings
  app/src/main/res/layout/fragment_external_content_setting.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_theme_setting.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#1249 Fix ThreadActionsBottomSheet crash on swipeAction
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: bug, quick

#1250 Homogeneize MergedContactsLive
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#1241 Fix InvalidMailboxes fetching Activities
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/NoMailboxActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug

#1253 Add more info in Sentry about `Message not found`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: enhancement

#1255 Request MailboxPassword
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordViewModel.kt
  app/src/main/res/layout/fragment_invalid_password.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1256 Add MergedContactDictionary typealias
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: enhancement

#1263 Fix too long processing when detecting quotes by removing siblings detection
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: bug, optimization

#1262 Inject navigation args in viewModels
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
Labels: optimization

#1264 Add trim() extension for TextInputEditText
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: enhancement, optimization

#1260 Update Signatures if our `identityId` doesn't exist anymore, then fallback on the new default one
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#1257 Add Sentry at each step of Notification creation, so we know when it fails exactly
  app/src/main/java/com/infomaniak/mail/data/api/UnwrappingJsonListSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: enhancement

#1268 Fix nonspam icon
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: quick

#1269 Fetch Signatures in MainActivity `onStart` instead of NewMessage opening
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: feature

#1259 Add Matomo for Notification actions
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
Labels: enhancement

#1266 Add Breadcrumb in Realm migrations
  app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: enhancement

#1258 Search `folderId` can't be `null` anymore
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug

#1272 Typo in MoveFrgament
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
Labels: optimization, quick

#1275 Fix Realm adapters IllegalStateExceptions
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/CoroutineScopeUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: bug

#1248 Add ExternalRecipient tag
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactChipAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/RoundedBackgroundSpan.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/ExternalUtils.kt
  app/src/main/res/color/chip_contact_background_color_external.xml
  app/src/main/res/color/chip_contact_text_color_external.xml
  app/src/main/res/drawable/ic_external_information.xml
  app/src/main/res/font/external_tag_font.xml
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1277 Execute ThreadListAdapter `formatList()` in `IO` instead of `Main`
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: optimization

#1280 `ThreadListAdapter.onSwipeFinished()` is now correctly optional
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: optimization

#1273 Split `foldersLive` into `defaultFoldersLive` & `customFoldersLive`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: enhancement

#1281 Make `FolderAdapter` injectable
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
Labels: feature

#1283 Make the clickable area for the chevron bigger
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/IndentableFolder.kt
  app/src/main/res/layout/view_decorated_text_item.xml
  app/src/main/res/values/dimens.xml
Labels: optimization

#1278 Fix email sending due to StyledRecipient
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactChipAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
Labels: bug

#1279 Add Matomo for External Recipient feature
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#1290 Rename `ikMail` configuration into `Mail`
  .github/workflows/sentry-release.yml
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: feature

#1292 Rename the rest of `ikMail` into `Mail`
  README.md
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
  fastlane/metadata/android/de/full_description.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/android/fr/full_description.txt
  fastlane/metadata/android/it/full_description.txt
  fastlane/metadata/android/sp/full_description.txt
Labels: feature

#1288 fix: Message has empty from from ThreadAdapter
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: bug

#1291 Rename `ikMail` JS into `kMail`
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
  app/src/main/res/raw/javascript_bridge.js
  app/src/main/res/raw/munge_email.js
  app/src/main/res/raw/style.css
Labels: feature

#1293 Rename `ikMail` icons into `Mail`
  app/src/main/res/drawable-night/ic_logo_infomaniak_mail.xml
  app/src/main/res/drawable/ic_logo_infomaniak_mail.xml
  app/src/main/res/raw/illustration_no_mailbox.json
  app/src/main/res/raw/illustration_onboarding_1.json
  app/src/main/res/raw/illustration_onboarding_2.json
  app/src/main/res/raw/illustration_onboarding_3.json
  app/src/main/res/raw/illustration_onboarding_4.json
Labels: feature, quick

#1295 Update bottom sheet style to match design system
  app/src/main/res/values/styles.xml
Labels: quick

#1296 Add Sentry for Notification action failure
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
Labels: enhancement

#1297 Add explanatory comments for Sentry in Notifications
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: enhancement, quick

#1294 Add exception in "RefreshThreads failed" Sentry
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: enhancement

#1282 Move `FolderAdapter.setFolders()` code to correct dispatcher
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
Labels: optimization

#1298 Fix HTML interpretation when editing a Draft
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug, quick

#1302 Trigger sound & vibration only once per Notification
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
Labels: bug, quick

#1300 Remove infinite refresh when DraftsActionsWorker triggers
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug

#1303 Hilt support for NotificationUtils
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1304 Rename app into `Infomaniak Mail`
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1305 fix: Notification actions doesn't work sometimes
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
Labels: bug

#1309 feat: Add an utility to manage logout with hilt
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/ui/login/NoMailboxActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt
Labels: enhancement

#1310 fix: Multiple instance errors for mailbox info
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/di/RealmDatabaseModule.kt
  app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: bug, enhancement

#1312 Delete orphans after sending a Sentry, so it doesn't spam Sentry anymore
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: optimization
