Repository Infomaniak/android-kMail, pull requests merged in 2023-10, with the labels that each got.

#1395 Try to fix `MESSAGE_NOT_FOUND`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: bug, enhancement, optimization

#1401 Reduce code complexity
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization

#1406 Fix returned Threads list from Threads algo
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: bug

#1407 Reduce parameters complexity in `RefreshController`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization

#1410 Fix DE translation
  app/src/main/res/values-de/strings.xml
Labels: enhancement

#1412 Fix Mailboxes being displayed twice after a logout
  app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt
Labels: bug, quick

#1417 Add random AI prompt examples as placeholders
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt
  app/src/main/res/layout/fragment_ai_prompt.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#1422 Add ai writer to the message composition view
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/FeatureFlagController.kt
  app/src/main/java/com/infomaniak/mail/data/models/FeatureFlag.kt
  app/src/main/java/com/infomaniak/mail/data/models/ai/AiMessage.kt
  app/src/main/java/com/infomaniak/mail/data/models/ai/AiPromptOpeningStatus.kt
  app/src/main/java/com/infomaniak/mail/data/models/ai/AiResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/ai/AssistantMessage.kt
  app/src/main/java/com/infomaniak/mail/data/models/ai/UserMessage.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SimpleIconPopupMenu.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/DecoratedItemView.kt
  app/src/main/res/color/color_ai_translucent_ripple.xml
  app/src/main/res/color/color_primary_translucent_ripple.xml
  app/src/main/res/color/color_primary_translucent_text_highlight.xml
  app/src/main/res/color/scrim_translucent.xml
  app/src/main/res/drawable-night/illustration_discover_ai.xml
  app/src/main/res/drawable/ic_ai_amical.xml
  app/src/main/res/drawable/ic_ai_formal.xml
  app/src/main/res/drawable/ic_ai_lengthen.xml
  app/src/main/res/drawable/ic_ai_magic_wand.xml
  app/src/main/res/drawable/ic_ai_regenerate.xml
  app/src/main/res/drawable/ic_ai_shorten.xml
  app/src/main/res/drawable/illustration_discover_ai.xml
  app/src/main/res/font/tag_font.xml
  app/src/main/res/layout/dialog_ai_replace_content.xml
  app/src/main/res/layout/fragment_ai_prompt.xml
  app/src/main/res/layout/fragment_ai_proposition.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/item_search_view.xml
  app/src/main/res/menu/ai_refining_options.xml
  app/src/main/res/navigation/new_message_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature, quick

#1424 fix: Split body throw an IllegalStateException sometimes
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: bug

#1425 Add Sentry for Quotas
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: bug, quick

#1426 Update AI replacement dialog's description
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#1429 Various enhancements for Sentry in Notifications
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
Labels: bug, enhancement

#1427 Fix unusable AI shortcuts
  app/src/main/java/com/infomaniak/mail/data/models/ai/AiMessage.kt
Labels: bug, quick

#1430 Update Sentry level for failed Notifications
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: optimization

#1432 Fix quotas NumberFormatException
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
Labels: bug, quick

#1431 Add loadMore and switchIdentity Matomo tracker
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
Labels: enhancement, quick

#1433 Update some Sentry
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: optimization

#1434 Fix LoadMore button not displayed on laggy devices
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: bug, quick

#1435 Fix LoadMore button blink on first dataset creation
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: bug, quick

#1438 Transform Refresh callbacks into data class
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: optimization

#1439 Update MessageNotFound Sentry
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization

#1437 Fix loader that wasn't disappearing sometimes
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: bug

#1436 Add Matomo for the AI feature
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/res/navigation/new_message_navigation.xml
Labels: feature

#1441 Activate externals for mailto
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
Labels: enhancement, quick

#1440 Add transition when replacing prompt with ai's generated proposition
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
  app/src/main/res/layout/fragment_ai_proposition.xml
Labels: enhancement, quick

#1442 Fix bottom sheet matomo mistakenly being sent when activity is recreated
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
Labels: bug, quick

#1445 Rename `flatMapFolderChildren()` into `flattenFolderChildren()`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization

#1446 Replace our own `RealmListSerializer` with Realm's `RealmListKSerializer`
  app/src/main/java/com/infomaniak/mail/data/api/RealmListSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: optimization

#1449 Fix ai inflation crash due to color resource used as image view's src
  app/src/main/res/layout/fragment_new_message.xml
Labels: bug, quick

#1443 Show all progress after a timer
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
Labels: enhancement, quick

#1451 Fix ANR and crash in SignatureSettingsFragment
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#1385 Scroll to correct Message when all expanded Messages are done loading
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: enhancement

#1453 Clean code Before leaks fixing
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/BaseAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/InputAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPromptFragment.kt
Labels: enhancement, quick

#1444 Fix BottomSheet not letting the keyboard popup
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
Labels: bug, quick

#1452 AI sliding animation to the AI PromptFragment
  app/src/main/java/com/infomaniak/mail/data/models/ai/AiPromptOpeningStatus.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/res/color/scrim_translucent.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#1447 Add SubBody in Realm
  app/src/main/java/com/infomaniak/mail/data/api/FlatteningSubBodiesSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/api/RealmInstantSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/api/UnwrappingJsonListSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/SubBody.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: feature

#1450 Display SubBodies
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
Labels: feature

#1455 Add Sentry when displaying an Email with SubBodies
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
Labels: feature, dependent

#1458 Fix binding NPE in `onDestroyView()`
  .idea/codeStyles/Project.xml
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/FlatteningSubBodiesSerializer.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
Labels: bug, quick

#1457 Fix empty backups
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1462 Clean XML code & imports
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/activity_no_mailbox.xml
  app/src/main/res/layout/fragment_intro.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/layout_attachments.xml
  app/src/main/res/layout/view_decorated_text_item.xml
  app/src/main/res/layout/view_recipient_field.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/new_message_navigation.xml
Labels: optimization

#1461 Fix timer not cancelled
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
Labels: bug

#1465 Move `newMessage` package outside of `main` package
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/BackspaceAwareChip.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/BackspaceAwareTextInput.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactChipAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ToggleableTextFormatterItemView.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/layout/chip_contact.xml
  app/src/main/res/layout/fragment_ai_prompt.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/view_recipient_field.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/new_message_navigation.xml
Labels: optimization, quick

#1472 Sanitize Notifications' preview
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: optimization

#1476 fix: Deleting an attachment triggers an IndexOutOfBoundsException
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
Labels: bug, quick

#1473 Fix Alert Dialog leaks
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/BaseAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/InputAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadModeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization

#1481 Rename FragmentContainerView IDs to avoid ambiguity
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/layout/activity_no_valid_mailboxes.xml
Labels: optimization

#1478 Update AI error design
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SimpleIconPopupMenu.kt
  app/src/main/java/com/infomaniak/mail/views/InformationBlockView.kt
  app/src/main/res/color/secondary_text_color_disabled.xml
  app/src/main/res/layout/fragment_ai_proposition.xml
  app/src/main/res/layout/view_information_block.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#1480 Add Matomo in Sync
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncInstallFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncStartFragment.kt
  app/src/main/res/layout/activity_sync_auto_config.xml
Labels: feature, dependent

#1483 Correctly use `preview` when there is no `body` in Notification
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: optimization

#1479 Fix already-sync snackbar that wasn't appearing
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncStartFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug

#1485 Add matomo for dismissing the ai error prompt using the close button
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
Labels: feature, quick

#1486 Fix negative Quotas by using Long instead of Int
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug

#1488 Update text color in simple menu popup
  app/src/main/java/com/infomaniak/mail/utils/SimpleIconPopupMenu.kt
  app/src/main/res/color/primary_text_color_disabled.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: quick

#1474 Scroll to top when changing Folder
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug

#1490 Fix NPE because of Thread too long
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug

#1493 Add Data class for the callbacks
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#1496 Fix remaining leaks
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
Labels: optimization

#1500 Use standardize to accurately compare emails
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
Labels: bug, quick

#1501 Factorize usage of LocalSettings in MainActivity
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: optimization

#1502 Add TitleAlertDialog
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/TitleAlertDialog.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1503 Clean AlertDialogs code
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/InformationAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/TitleAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
Labels: optimization

#1506 Correctly trigger displaying of popup linked to `appLaunches`
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
Labels: bug

#1507 Only display Sync tip if not already synchronized
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncConfigureFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug

#1505 Update sync illustration and wording
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/SyncDiscoveryBottomSheetDialog.kt
  app/src/main/res/drawable-night/illustration_discover_sync.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_sync_onboarding.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1508 Clean code
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/res/layout/fragment_new_message.xml
Labels: optimization

#1510 Automatically detect subject in ai proposition and insert it in the correct field
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/AiDescriptionAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1511 Add matomo events for ai subject replacement dialog
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
Labels: feature, quick

#1513 External banner manually closed persists across navigations
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: bug, quick

#1509 Don't blink when updating Message status (favorite, seen, etc…)
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#1514 Update strings
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/TitleAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#1517 Also change the background color of `webViewsFrameLayout` when toggling light mode for a Message
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: bug

#1516 Clean Onboarding code
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/res/layout/fragment_intro.xml
Labels: optimization

#1519 Fix missing ai proposition when recreating the fragment with an error displayed
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
Labels: quick

#1518 AI engine choice is now possible
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/AiEngineSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiEngineChoiceFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/res/drawable/ic_ai_engine_chat_gpt.xml
  app/src/main/res/drawable/ic_ai_engine_falcon.xml
  app/src/main/res/drawable/ic_external_information.xml
  app/src/main/res/layout/fragment_ai_engine_choice.xml
  app/src/main/res/layout/fragment_ai_engine_setting.xml
  app/src/main/res/layout/fragment_ai_prompt.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/layout_ai_engine_choice.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/navigation/new_message_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1520 Clean code after merge of `ai-engine-choice`
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/drawable/ic_ai_engine_falcon.xml
  app/src/main/res/layout/fragment_ai_engine_setting.xml
Labels: optimization

#1522 Fix automatically detected wording errors in strings
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#1524 Update AI wording to make it easier to understand
  app/src/main/res/layout/fragment_ai_engine_choice.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#1523 Fix compose Subject field autocompletion for SwiftKey
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ComposeSubject.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/res/layout/fragment_new_message.xml
Labels: bug

#1526 Easter egg Halloween
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/raw/easter_egg_halloween.json
Labels: feature

#1525 Email subjects can be copied with a long press
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/fragment_ai_proposition.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature
