Repository Infomaniak/android-kMail, pull requests merged in 2023-07, with the labels that each got.

#1090 fix: Ignore errors due to Account switching
  app/src/main/java/com/infomaniak/mail/utils/CoroutineScopeUtils.kt
Labels: bug, enhancement

#1094 NullPointerException when getting completed Draft worker results
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#1089 Rename `kMail` into `ikMail`
  .github/workflows/sentry-release.yml
  README.md
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
  app/src/main/res/drawable-night/ic_logo_infomaniak_mail.xml
  app/src/main/res/drawable/ic_logo_infomaniak_mail.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/raw/illu_no_mailbox.json
  app/src/main/res/raw/illu_onboarding_1.json
  app/src/main/res/raw/illu_onboarding_2.json
  app/src/main/res/raw/illu_onboarding_3.json
  app/src/main/res/raw/illu_onboarding_4.json
  app/src/main/res/raw/javascript_bridge.js
  app/src/main/res/raw/munge_email.js
  app/src/main/res/raw/style.css
  app/src/main/res/values/strings.xml
  fastlane/metadata/android/de/full_description.txt
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/android/fr/full_description.txt
  fastlane/metadata/android/it/full_description.txt
  fastlane/metadata/android/sp/full_description.txt
  settings.gradle
Labels: feature

#1096 Matomo: Add missing tracker
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: feature, quick

#1099 Fix create folder
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug, enhancement

#1091 Display Folder pastille if there's unread Messages
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/ActivitiesResult.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/res/drawable/ic_pastille.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1100 Remove unused variable in Thread
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: optimization, quick

#1102 Improve Realm usage
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: bug, enhancement

#1101 Display Mailbox pastille if there's unread Messages
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/UnreadDisplay.kt
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/item_menu_drawer.xml
Labels: feature

#1103 Refactor controllers
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/AttachmentController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1076 Threads are now refreshed once instead of thrice when coming back to app
  app/src/fdroid/java/com/infomaniak/mail/GplayUtils.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/GplayUtils.kt
Labels: bug, quick

#1107 Action snackbar is now displayed ASAP, instead of waiting for all Folders to be refreshed
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: enhancement

#1108 fix: Problem when returning to the app
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
Labels: bug

#1110 fix: The Realm is still closed early
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
Labels: bug, enhancement

#1095 Unlock Invalid password's mailboxes
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MailboxListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/res/layout/fragment_invalid_password.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1109 Unread pastille is now correctly hidden if the warning icon is displayed
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
Labels: bug

#1111 fix: Realm is still in operation even though it is closed
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug, enhancement

#1112 fix: Manage the possibility that a thread may contain messages
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug

#1119 Fix messages shortuid
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug, enhancement

#1120 Improve search
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: bug, enhancement

#1121 fix: When the search is stopped on return, the data disappears
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: bug, enhancement

#1122 Update italian string
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1117 Invalid mailboxes screen
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/LockedMailboxBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MailboxListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
  app/src/main/res/layout/activity_no_valid_mailboxes.xml
  app/src/main/res/layout/fragment_no_valid_mailboxes.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/navigation/no_valid_mailboxes_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1123 Fix incorrect folder being selected in search after opening a thread
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: bug, quick

#1124 Update AttachMailbox layout and error management
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
  app/src/main/res/layout/fragment_attach_mailbox.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1126 Fix loosing new message content when recreating the activity twice
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug

#1125 Fix search v3
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: bug, enhancement

#1134 Use material native icon
  app/src/main/res/drawable/ic_show_password.xml
  app/src/main/res/layout/fragment_attach_mailbox.xml
  app/src/main/res/layout/fragment_invalid_password.xml
Labels: enhancement

#1131 feat: Init Realm migration
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
Labels: bug, enhancement

#1130 Clean code
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt
  app/src/main/java/com/infomaniak/mail/ui/BaseActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IlluColors.kt
  app/src/main/java/com/infomaniak/mail/ui/login/NoMailboxActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterFirebaseBroadcastReceiver.kt
Labels: optimization

#1137 fix: SearchAdapter has not been initialized
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: bug

#1146 fix: It's possible to return to the launch
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
Labels: bug

#1138 Mark Message as read when answering to it
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
Labels: bug

#1145 fix: Refresh may run to infinity when you refresh after sending
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: bug

#1150 feat: Register firebase in the app's `onCreate` lifecCycle with a delay
  app/src/standard/java/com/infomaniak/mail/StandardMainApplication.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
Labels: enhancement

#1148 Signature selection
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/SignatureAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/item_signature.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: feature

#1149 Remove unnecessary draft creation
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization, quick

#1140 Add Notification's Reply action
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#1157 Fix wrong `requestCode` for Reply action in Notification
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: bug

#1158 Can open .apk in attachment
  app/src/main/AndroidManifest.xml
Labels: enhancement

#1162 Heuristic to preselect best signature when replying
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/SignatureAdapter.kt
Labels: enhancement

#1156 Fix `Message.inReplyTo` with `UnwrappingJsonListSerializer`
  app/src/main/java/com/infomaniak/mail/data/api/UnwrappingJsonListSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: bug

#1161 Use correct texts in MultiSelect Delete dialog
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
Labels: bug

#1160 Prepare code for Notifications Actions
  app/src/main/java/com/infomaniak/mail/di/ApplicationModule.kt
  app/src/main/java/com/infomaniak/mail/di/CoroutinesQualifiers.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/standard/java/com/infomaniak/mail/firebase/KMailFirebaseMessagingService.kt
Labels: optimization

#1154 Add Archive & Delete actions in Notifications
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationJobsBus.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationPayload.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: feature

#1168 Display "Not spam" instead of "Junk" in Spam Folder
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
Labels: feature

#1167 Display MessageActions instead of ThreadActions when multiselect on 1 Thread of 1 Message
  app/src/main/java/com/infomaniak/mail/data/models/thread/SelectedThread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
Labels: bug

#1164 Leave Thread when marking Message as unread
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: feature

#1173 Add scroll view to AttachMailboxFragment for small screen
  app/src/main/res/layout/fragment_attach_mailbox.xml
Labels: enhancement, quick

#1153 Refactor folders items
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/DecoratedTextItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/IndentableFolder.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/InvalidMailboxItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/MenuDrawerFolderItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/MenuDrawerMailboxItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/SelectableFolderItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/SelectableMailboxItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/SelectableTextItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/SimpleMenuDrawerItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/UnreadItemView.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/item_folder_menu_drawer.xml
  app/src/main/res/layout/item_invalid_mailbox.xml
  app/src/main/res/layout/item_mailbox_menu_drawer.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/layout/item_search_folder.xml
  app/src/main/res/layout/item_selectable_folder.xml
  app/src/main/res/layout/item_selectable_mailbox.xml
  app/src/main/res/layout/view_decorated_text_item.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#1165 Remove ioDispatcher from adapter
  app/src/main/java/com/infomaniak/mail/ui/main/MailboxListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesFragment.kt
Labels: enhancement, quick

#1174 Inject context instead of passing it through every constructors
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization, quick

#1170 Don't delete subFolder and init them correctly
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug

#1175 Remove Signatures Sentries that have been fixed
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: optimization

#1176 Fix not getting the recently fetched signatures in NewMessageActivity
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: bug

#1178 Assign correct `mailboxId` at 1st connection
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
Labels: bug, quick

#1179 Add Folders collapsing
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerDropdownView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/views/CollapsableItem.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/IndentableFolder.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/MenuDrawerFolderItemView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/SelectableFolderItemView.kt
  app/src/main/res/layout/view_decorated_text_item.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1180 Simplify code using a groupBy
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization, quick

#1182 Add download snackbar
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, quick

#1185 Fix focus when opening existing Draft
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug, quick

#1186 Add subFolder chevron rotation
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerDropdownView.kt
  app/src/main/java/com/infomaniak/mail/views/decoratedTextItemView/MenuDrawerFolderItemView.kt
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
Labels: feature
