Repository Infomaniak/android-kMail, pull requests merged in 2023-11, with the labels that each got.

#1528 feat: Check if an account already exist in kSync
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: feature

#1527 Update feature flag api call with new specs
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/FeatureFlagController.kt
  app/src/main/java/com/infomaniak/mail/data/models/FeatureFlag.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: enhancement

#1529 Fix some NullPointerException
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, quick

#1530 Use the latest css naming convention
  app/src/main/res/raw/improve_rendering.css
Labels: quick

#1531 Optimize parallelization of API updates at application boot
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization

#1532 Enhance stuff
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/models/FeatureFlag.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: enhancement

#1535 Use material bottom sheet handle for accessibility purposes
  app/src/main/res/drawable/bottom_sheet_drag_handle.xml
  app/src/main/res/layout/bottom_sheet_restore_emails.xml
  app/src/main/res/layout/view_bottom_sheet_separator.xml
Labels: feature, quick

#1538 Don't delete Attachment upload local file if another Attachment is the same
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, quick

#1539 Fix Attachment content overriding
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#1541 Handle Messages that don't have references to all previous Messages of the Thread
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug

#1534 Stop detecting simple blockquotes to collapse replies
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: bug, enhancement

#1536 Refactor handling of collapsed responses per message of a Thread
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: enhancement

#1537 Automatically expand quotes of threads of one message
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: feature, rebase

#1544 Revert "Merge pull request #1541 from Infomaniak/fix-duplicated-threads"
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug

#1545 Delete duplicated Threads after updating all existing Threads
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug

#1543 Add Sentry if the threadsView will be displayed empty
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement, quick

#1549 Improve email rendering by breaking wide lines
  HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/BodyCleaner.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
Labels: enhancement

#1550 Fix render long lines for selection or copy
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
Labels: bug, enhancement

#1547 Use `getReferenceMessages()` instead of `getReferenceThread()` to correctly handle duplicated Threads in all folders
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: bug

#1551 Fix Externals detection due to race condition between 2 LiveData
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageUtils.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/utils/ExternalUtils.kt
Labels: bug

#1553 Use Android formatter instead of the Core one for Quotas display
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
Labels: bug

#1561 Update the style of unread emails to make them stand out more
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: enhancement, quick

#1558 Unprivate `companions` for the sake of simplicity
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroPagerAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/RecentSearchAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/RoundedBackgroundSpan.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionItemView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SimpleIconPopupMenu.kt
Labels: enhancement

#1562 Supports long press on URLs inside of an email
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/BaseAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/InputAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/LinkContextualMenuAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/dialog_link_contextual_menu.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1554 AI uses the previous Message as context to be more accurate when answering
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/ai/ContextMessage.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1555 Factorize `subBodies` fusion
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
Labels: feature

#1556 Flow for when the user replies to a message too big to be handled by the AI
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiSharedData.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1559 Clean `companions` content
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/models/AppSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
Labels: enhancement

#1576 Fix wbr algorithm so it doesn't remove important whitespaces and new lines
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
Labels: bug
