Repository Infomaniak/android-kMail, pull requests merged in 2023-02, with the labels that each got.

#535 Remove wrong `MissingPermission` lint
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug

#538 fix: draft actions service not stopped
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#537 fix: out of memory when delete messages delta
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: bug

#513 Display the correct Message in `SENT` folder
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/Thread.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug

#528 Update MenuDrawer badge for DRAFT, SENT & TRASH
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
Labels: feature, dependent

#540 Wait at most 6s instead of at least 6s before refreshing Drafts service
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#541 Clean `handleDeletedUids()` code after fixing OOM error
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: optimization

#542 fix: ForegroundServiceStartNotAllowedException
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#539 fix: setPreviousMessage in draft with incorrect thread
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: bug

#545 Fix back from thread when thread is updated
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: bug

#543 Add Sentry for missing/orphans Threads/Messages/Drafts
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: feature

#546 Disable some features
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/res/layout/fragment_settings.xml
Labels: optimization

#549 fix: Can't toast on a thread that has not called Looper.prepare()
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
Labels: bug

#557 Update some missing years in copyrights
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsViewModel.kt
Labels: optimization

#548 Fix orphan Messages
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug

#555 fix: remove multiple whitespaces if needed
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug

#559 Update some Ui elements of the settings
  app/src/main/res/drawable-night/bg_list_density_large.xml
  app/src/main/res/drawable-night/ic_swipe_left_long_pink.xml
  app/src/main/res/drawable-night/ic_swipe_right_long_pink.xml
  app/src/main/res/drawable/bg_list_density_large.xml
  app/src/main/res/drawable/ic_swipe_left_long_pink.xml
  app/src/main/res/drawable/ic_swipe_right_long_pink.xml
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
  app/src/main/res/layout/swipe_illustration_content.xml
Labels: enhancement

#561 fix: Handle all api errors exception in SyncMessageWorker
  app/src/main/java/com/infomaniak/mail/utils/Exceptions.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug

#563 Display Actions snackbar above Thread ActionsBar & ThreadList FAB
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: enhancement, quick

#562 Comply with material guidelines for icon buttons target size and update to follow mockups
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/item_search_view.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/layout/view_recipient_field.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#514 Update action bottom sheet + Fix some UI
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionItemView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
  app/src/main/res/drawable/ic_contact_action_add_user.xml
  app/src/main/res/drawable/ic_email_action_move.xml
  app/src/main/res/drawable/ic_email_action_rule_filter.xml
  app/src/main/res/drawable/ic_email_action_save_as_pdf.xml
  app/src/main/res/drawable/ic_feedbacks.xml
  app/src/main/res/drawable/ic_report_junk.xml
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
  app/src/main/res/layout/bottom_sheet_junk.xml
  app/src/main/res/layout/view_main_actions.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#566 First update for the new dark theme
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/view_menu_drawer_dropdown.xml
  app/src/main/res/layout/view_recipient_field.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: quick

#551 Add Move action
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
  app/src/main/res/drawable/ic_folder_add.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_move.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: feature

#552 refactor(Move): Factorize Move and Archive functions
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: enhancement

#553 refactor(Move): Create abstract class MenuFoldersFragment
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
Labels: enhancement

#560 refactor(Action): Hide postpone action for v1
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
Labels: quick

#567 Fix disconnection dialog wording
  app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
  app/src/main/res/layout/dialog_confirm_logout.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: quick

#569 Don't reset Folder to `DEFAULT_SELECTED_FOLDER` when MainActivity is recreated
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug

#576 Update attachment icon size and clean code
  app/src/main/res/layout/item_attachment.xml
Labels: quick

#580 Fix `markAsReadUnread` back navigation when closed
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: bug

#583 Fix draft text size
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/values/styles.xml
Labels: bug, quick

#585 fix: current user is null
  app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
Labels: bug, quick

#579 Fix missing bottom margin
  app/src/main/res/raw/add_padding.css
Labels: bug, quick

#586 Directly use `strokeColor` variable instead of `setStrokeColor()`
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: optimization

#570 Sort "ThreadList header fix" code
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization

#587 Update color for toolbar navigation icons
  app/src/main/res/layout/fragment_move.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, quick

#572 Thread: Use `folder` backlink instead of `folderId` to optimize queries
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: optimization

#573 Message: Use `folder` backlink instead of `folderId` to optimize queries
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: optimization

#592 Remove resources from old card design for thread
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: quick

#590 Update recipient chip ui to match the specs
  app/src/main/res/values/styles.xml
Labels: quick

#574 Clarify Threads creation algorithm
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Thread.kt
Labels: optimization

#595 Adapter is notified after `onDestroy()` is called
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAdapter.kt
Labels: bug

#598 refactor(ApiRoutes): Rename methods doing action on messages
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
Labels: enhancement

#589 Disable send button when there are no recipients and fix icons size
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/res/color/icon_button_primary_color.xml
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#600 Don't display JunkBottomSheetDialog for thread actions
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
Labels: feature

#593 Add Report Phishing action
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/res/layout/dialog_report_phishing.xml
Labels: feature

#594 Fix app crash on reopening logout dialog
  app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
Labels: bug, quick

#599 Update design of recipient autocomplete items
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values/dimens.xml
Labels: enhancement

#596 Create Extension fonction to factorize AlertDialog
  app/src/main/java/com/infomaniak/mail/ui/main/menu/ManageMailAddressFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/dialog_confirm_logout.xml
  app/src/main/res/layout/dialog_description.xml
Labels: enhancement, quick

#603 Update quick bottom action bar text color according to specs
  app/src/main/res/values/styles.xml
Labels: quick

#601 Add unknown recipient button when composing new message
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/drawable/ic_unknown_user_avatar.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#597 Don't add Messages in Folder if they are already there
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
Labels: bug

#602 Factorize snackbar in a manager for ease of use
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/SnackBarManager.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: enhancement

#605 Add Sentry URL breadcrumb
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: feature

#610 update current SyncMessagesWorker on a new schedule request
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug, enhancement, quick

#608 Fix scroll in Folders views
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_move.xml
Labels: bug

#607 Move Inbox to `defaultFolders`
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_move.xml
Labels: feature

#606 Display sub-folders for `defaultFolders`
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: feature

#612 Sort `customFolders` by name
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: feature

#615 Fix delete outdated folders
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug

#609 Refresh Folders when MainActivity `onStart`
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
Labels: feature

#621 Use `copyFromRealm()` instead of `toRecipientsList()`
  app/src/main/java/com/infomaniak/mail/data/models/Thread.kt
Labels: optimization

#617 Add BlockUser action
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#620 Order actions
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization

#619 Refactor `shortUid` use
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: optimization

#622 Update `textInputStrokeColor` according to specs
  app/src/main/res/color/text_input_layout_box_color.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: quick

#582 Manage SwipeActions variants
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/res/drawable/ic_drawer_inbox.xml
  app/src/main/res/drawable/ic_envelope_open.xml
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/drawable/ic_star_filled.xml
  app/src/main/res/drawable/ic_unstar.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: feature

#630 fix: Remove multiple whitespaces
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug, quick

#633 Remove Elvis (sorry bro) so the app can crash if there’s an issue
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization

#636 Focus correct field when composing a new message
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
Labels: enhancement, quick

#629 Add `writeEmail` action to Contact bottomSheet
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#631 Remove commented API calls
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
Labels: optimization

#638 Clean code
  app/src/main/java/com/infomaniak/mail/data/models/AppSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: optimization

#634 Copy email address to clipboard
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
Labels: feature

#578 Disable possibility to fetch multiples Folders at the same time
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug

#641 Replace deprecated `onBackPressed` with `onBackPressedDispatcher`
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
Labels: optimization

#642 Correctly popBackStack & finish when needed
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: bug, quick

#639 Fetch Folders after saving a Draft, so it automagically displays itself in ThreadFragment
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: feature, quick

#640 Display Draft toast before finishing Activity
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug, quick

#588 Correctly update `unreadCount` of all impacted Folders when receiving new Message
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: bug, quick

#644 refactor: move thread to thread package
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/ThreadResult.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: enhancement, dependent, quick

#626 Add Search history support
  app/src/main/java/com/infomaniak/mail/ui/main/search/RecentSearchAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_recent_search.xml
Labels: feature, dependent

#627 Support `swipeRefresh` on Search results
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: feature

#632 Add custom pagination for the Search
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: feature

#646 Remove unused imports
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: quick

#645 Update background color for new message dark theme
  app/src/main/res/layout/fragment_new_message.xml
Labels: quick

#649 Fix history delete cross icon size
  app/src/main/res/layout/item_recent_search.xml
Labels: bug, quick

#648 Small code enhancements upon Search feature codebase
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/HeaderItemDecoration.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
Labels: optimization
