Repository Infomaniak/android-kMail, pull requests merged in 2023-12, with the labels that each got.

#1568 Create custom view for attachment
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt
  app/src/main/res/layout/item_attachment.xml
  app/src/main/res/layout/view_attachment_details.xml
  app/src/main/res/values/attrs.xml
Labels: feature

#1587 Update switches to material3 by using the correct View and not the obsolete one
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
  app/src/main/res/layout/view_item_setting.xml
Labels: enhancement, quick

#1588 Latest empty states
  app/src/main/res/drawable-night/ic_empty_state_folder.xml
  app/src/main/res/drawable-night/ic_empty_state_inbox.xml
  app/src/main/res/drawable-night/ic_empty_state_network.xml
  app/src/main/res/drawable-night/ic_empty_state_search.xml
  app/src/main/res/drawable-night/ic_empty_state_trash.xml
  app/src/main/res/drawable-night/ic_invalid_mailbox.xml
  app/src/main/res/drawable/ic_empty_state_folder.xml
  app/src/main/res/drawable/ic_empty_state_inbox.xml
  app/src/main/res/drawable/ic_empty_state_network.xml
  app/src/main/res/drawable/ic_empty_state_search.xml
  app/src/main/res/drawable/ic_empty_state_trash.xml
  app/src/main/res/drawable/ic_invalid_mailbox.xml
Labels: enhancement

#1589 Make profile button easier to click
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/view_avatar.xml
  app/src/main/res/values/attrs.xml
Labels: enhancement, quick

#1571 T01: Clean code before adding Tablet mode
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/res/layout/fragment_invalid_password.xml
Labels: enhancement

#1574 T02: Move ThreadListAdapter `formatList()` out of companion
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: optimization

#1575 T03: Sort Thread code before adding Tablet mode
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: optimization

#1596 Do not interpret text/plain emails when replying or forwarding an email
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: bug, quick

#1570 Save to kDrive
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AttachmentIntentUtils.kt
  app/src/main/res/layout/bottom_sheet_attachment_actions.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#1598 Remove useless annotation
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/BaseAlertDialog.kt
Labels: enhancement

#1601 fix: Notifications are displayed on top of the screen
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
Labels: enhancement, quick

#1572 T04: Clean Thread code before adding Tablet mode
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#1573 T05: Barebone Tablet mode
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  gradle/libs.versions.toml
Labels: feature

#1578 T06: Add selection background when clicking on a Thread
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
Labels: feature

#1599 Xmas easter egg
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/raw/easter_egg_xmas.json
Labels: feature

#1607 Enable collapsing for default folders
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
Labels: feature, quick

#1579 T07: Display Folder name in Thread empty view
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/res/layout/fragment_thread.xml
Labels: feature

#1580 T08: Update ThreadFragment toolbar icon when rotating device
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#1581 T09: Handle back pressed on Tablet mode
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
Labels: enhancement

#1582 T10: Close Thread when marking it as read
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: feature

#1583 T11: Close Thread when switching Folder
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
Labels: feature

#1585 T13: Update MultiSelection when deleting open Thread
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
Labels: bug, dependent

#1602 Escape subject and recipients when inserting them in reply/forward
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
Labels: bug

#1603 Extract reply/forward header creation code in their own use case file
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
Labels: enhancement

#1605 Remove class and id that were copied from the webmail but are actually useless
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
Labels: enhancement, quick, rebase

#1610 Update small bottom sheets UI oversights
  app/src/main/res/layout/bottom_sheet_multi_select.xml
  app/src/main/res/layout/bottom_sheet_reply.xml
Labels: enhancement, quick

#1608 Add transitions in menu drawer
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/res/layout/fragment_menu_drawer.xml
Labels: enhancement, quick

#1586 T14: Temporary fix of `statusBarColor`
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiEngineChoiceFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncConfigureFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug

#1592 T15: Tablet easter egg
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ConfettiUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/values/colors.xml
Labels: feature

#1593 T16: Sort navigation code
  .idea/navEditor.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: optimization

#1594 T17: Remove ugly types (Pair, Triple, etc…) in some LiveData
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#1595 T18: Simplify navigation to Thread
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization

#1597 T19: Correctly place Snackbar depending on currently displayed fragments
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#1609 T19.5: Add Avatar easter egg
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
Labels: feature, dependent

#1606 T20: Various Tablet improvements
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/drawable/ic_navigation_default.xml
  app/src/main/res/values/themes.xml
Labels: optimization

#1611 T21: Clean code
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AttachmentMimeTypeUtils.kt
  app/src/main/res/layout/fragment_ai_proposition.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/item_message.xml
Labels: enhancement
