Repository Infomaniak/android-kMail, pull requests merged in 2023-04, with the labels that each got.

#817 RecentSearches: Update `close` icon & Add `clock` icon
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_editor_clock.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_recent_search.xml
Labels: enhancement

#816 Make sure that Message's `body` is always there when replying to it
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug

#814 Headers now display the correct day when update is triggered
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug

#821 Fix crash in `computeInitials()` if Correspondent has only ponctuations in its name
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
Labels: bug, quick

#823 Add button to remove `quote` when composing email
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/res/layout/fragment_new_message.xml
Labels: feature

#829 Greys out already used emails when auto completing recipients
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/res/drawable/ic_check_rounded.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#832 Fix issue 831 - IllegalArgumentException: Tmp detached view should be removed from RecyclerView
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
Labels: bug

#830 Highlight matched text when adding Contact to an email
  app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
Labels: enhancement

#836 Disable the possibility to re-use ViewHolders for Thread fragment
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#840 Fix inline not loaded first time and similar Sentry issues
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
Labels: bug

#844 Add missing `resource` in Attachment when fetching it for a forwarded Draft
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
Labels: bug

#841 Add missing actions in Multiselection BottomSheet
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MainActionsView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/res/drawable/ic_non_spam.xml
  app/src/main/res/layout/bottom_sheet_multi_select.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/main_actions_multi_select_menu.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#850 Fix `inline` Attachment loaded several times
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
Labels: bug

#852 New Sentry
  app/src/main/AndroidManifest.xml
Labels: enhancement

#851 Fix elevated Toolbar and use it in NewMessage to match specs
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/values/colors.xml
Labels: bug, enhancement

#828 Stop notif permission requesting
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
Labels: bug, feature

#855 Fix hardcoded selected contact scrim color
  app/src/main/res/color/selected_contact_scrim.xml
  app/src/main/res/layout/item_contact.xml
Labels: bug, quick

#857 fix: DownloadManager for API below 29 need write permission
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
Labels: bug

#847 Switch Mailbox in AccountView
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerSwitchUserMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SimpleMailboxAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/item_mailbox_my_account.xml
  app/src/main/res/layout/item_switch_mailbox.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#849 Remove `isInMenuDrawer` default value
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
Labels: enhancement, quick

#864 Feat: Help button
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/main/menu/HelpFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/res/layout/fragment_help.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#863 fix: Octet-stream mime type has not been managed
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: bug, quick

#862 `IllegalArgumentException` when navigating from Thread fragment to DownloadAttachment dialog
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug, quick

#853 Don't start `DraftsActionsWorker` when adding Attachment
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug

#858 Display error & leave Compose screen if Draft init fails
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#865 Center Avatar, Subject, Recipients & Buttons vertically in Message view
  app/src/main/res/layout/fragment_intro.xml
  app/src/main/res/layout/item_message.xml
  gradle.properties
Labels: optimization

#859 Fields & chevron now correctly collapse/rotate when Recipients are added/deleted
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
Labels: bug

#866 When clicking on Thread, don't add `searchQuery` in `history` if it's too short
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: bug, quick

#867 Decrease code complexity in Search
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: optimization

#869 Use `.copyFromRealm()` to fix crash when Contacts are invalidated in Realm
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
Labels: bug

#870 If user tries to `mailTo:` without being connected, redirect to `LaunchActivity`
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
Labels: bug, quick

#872 Code cleaning
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: optimization

#875 Search: Only save previous state when opening Thread, and not in `onStop()`
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: bug

#879 Add missing `.copyFromRealm()` for MergedContacts
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug

#868 Add Sentry log + Fix crash when Threads & Messages are in multiple Folders at the same time
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
Labels: bug

#883 Attempt to fix IllegalArgumentException for RecyclerView
  app/src/main/res/layout/fragment_menu_drawer.xml
Labels: bug

#882 Sanitize `messageId` for Realm query
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: bug

#885 Align Date to baseline of expeditor instead of centering it vertically
  app/src/main/res/layout/item_message.xml
Labels: enhancement, quick

#886 Remove unused code in models
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/EmptyResponse.kt
  app/src/main/java/com/infomaniak/mail/data/models/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/MoveResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/data/models/Seen.kt
  app/src/main/java/com/infomaniak/mail/data/models/StarMessageResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBook.kt
  app/src/main/java/com/infomaniak/mail/data/models/addressBook/AddressBooksResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Contact.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Priority.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/SaveDraftResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/SendDraftResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/DeleteMessageResult.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: optimization

#881 Fix "alpha must be between 0 and 255"
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#880 Add some Sentry logs
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ApplicationMain.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  build.gradle
Labels: optimization

#892 Remove `editorCamera` icon
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/res/layout/activity_new_message.xml
Labels: enhancement, quick

#893 Remove `else` in `when` to avoid future issue when adding new SwipeActions
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement, quick

#894 Hide `print` & `reportDisplayProblem` actions
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
Labels: enhancement, quick
