Repository Infomaniak/android-kMail, pull requests merged in 2023-06, with the labels that each got.

#978 Lower the "Quote size detection" limit to match iOS modification
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: quick

#979 Fix PR about margins
  app/src/main/res/drawable/ic_chevron_right.xml
  app/src/main/res/layout/fragment_swipe_actions_settings.xml
  app/src/main/res/layout/swipe_left_illustration.xml
  app/src/main/res/layout/swipe_right_illustration.xml
  app/src/main/res/layout/view_item_setting.xml
Labels: enhancement

#981 Quick UI updates
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/res/drawable/ic_unstar.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: enhancement, quick

#970 Display a Snackbar when saving Draft and a Toast for `mailto:`
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/SnackBarManager.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, feature

#980 Add Matomo in DeleteDraft snackbar
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: quick

#972 Prevent from clicking multiple times a SnackBar action
  app/src/main/java/com/infomaniak/mail/ui/main/SnackBarManager.kt
Labels: bug, quick

#977 Swipe to dismiss snackbars
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/SnackBarManager.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_new_message.xml
Labels: enhancement

#982 UI for Mailboxes with outdated password
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/layout/item_menu_drawer.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#966 Revamped ThreadsAlgo to be able to paginate new Messages
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/ActivitiesResult.kt
Labels: enhancement, feature, optimization

#983 Add user feedback when expanding a still empty WebView
  app/src/main/res/layout/item_message.xml
Labels: enhancement, quick

#984 Remove useless startActivityForResult code
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: quick

#985 Toast for saving and sending drafts from mailto:
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
Labels: enhancement, quick

#989 Remove autoscroll to top when a new Thread is received
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterFirebaseBroadcastReceiver.kt
Labels: bug

#991 Cancelling the Threads algo doesn't cancel the parent coroutine anymore
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: bug

#992 Realm broadcasts twice when a Thread is deleted, so it crashs the navigation backstack
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#996 Don't scroll to top when going back from Thread screen to Threads list
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug

#999 Fix auto scroll to last unseen Message when opening a Thread
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#1002 fix: Inject AccountViewModel
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
Labels: bug

#1006 Add Sentry if we can't decode the API result when sending an email
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1008 Fix draft worker errors
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, enhancement

#1013 fix: Finish mailto activity the task is not cleared
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug, enhancement

#1016 Fix empty mailto recipient
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
Labels: bug, quick

#1007 Now displays the missing "saving draft" toast when putting the app in the background
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: enhancement

#1015 Fix draft saving when putting app in the background
  app/src/main/java/com/infomaniak/mail/di/ApplicationModule.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, enhancement

#1017 Fix scrolling to correct message when no messages are expanded
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#1018 Single-message thread actions are message's one
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement, quick

#1019 Remove useless isBlank() check
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
Labels: enhancement, quick

#1021 Search: Clean code
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: optimization, quick

#1022 Search: Reorganize `fetchThreads()` code
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: optimization, quick

#1023 Search: Rename `resourcePrevious` into `isFirstPage`
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: optimization, quick

#1025 Sort Message `initLocalValues()` code
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: optimization, quick

#1026 Messages from Search are not lost into Realm anymore
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: bug, quick

#1020 Manage mailto recipients with name and separated by semi colon
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
Labels: enhancement, quick

#1028 Search: Fix lost flags
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug, quick

#1029 Synchronize ViewModel & Realm drafts
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#1030 Keep Draft data in UI when recreating the Activity
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: bug

#1031 Swipe on single message Thread display message actions
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#1010 Reset Folder history when it's emptied
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
Labels: bug

#1032 Don't lose Mailbox local data when updating from remote
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
Labels: bug, quick

#1037 Expand the fab when we enter a folder
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug, quick

#1036 Correctly reset Folder when `paginationInfo` is `null`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: bug, quick

#1039 Add the settings dividers back
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioGroupView.kt
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: quick

#1038 Update "Load more" design
  app/src/main/res/layout/item_thread_load_more_button.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#1040 Update some logs + Reorganize MainViewModel code
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
Labels: optimization, quick

#1041 Update Signatures when updating Mailbox content
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug, quick

#1044 In Search, we don't loose Messages bodies anymore
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug

#1043 Only fetch Folders once at boot (and not twice)
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug

#1047 Notify user of Draft failure to send/save
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1048 Improve Draft send/save speed by returning from Worker before waiting to refresh Draft folder
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1053 Use `destructured` for `mailto:`
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
Labels: enhancement, quick

#1035 LoginActivity: Clean both `authenticateUser()` code
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
Labels: enhancement

#1052 Reduce cognitive complexity + Rename Notification builders
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1054 Optimize Folder history reset
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization, quick

#1046 Fix Draft with bad connection
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#1033 If needed, switch to `passwordValid` Mailbox, or logout
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1049 Manage locked Mailbox
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1055 Revamp Mailbox error
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: enhancement

#1057 Close keyboard when pressing "search" button while searching emails
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: bug, enhancement, quick

#1058 Fetch Signatures when opening a Draft
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
Labels: bug

#1059 Add missing API errors
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1060 Leave Composition screen if we can't get Signatures
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
Labels: bug

#1061 Block click on locked Mailbox + Display Toast
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/MenuDrawerItemView.kt
Labels: feature

#1056 Make the color of hypertext links the same as the theme of the app
  app/src/main/res/raw/style.css
Labels: enhancement, quick

#1064 fix: Folder realm closed from mainViewModel
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug

#1063 Fix draft being sent/saved multiple times instead of once
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug

#1065 fix: RemoveAll doesn't work for folders
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
Labels: bug

#1066 Correctly detect frelated Mailboxes at user login
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: bug, quick

#1067 Fix Activity re-creation kicking out of Draft redaction
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug

#1045 Dagger / Hilt / Realm
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/AttachmentController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/AddressBookController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/di/RealmDatabaseModule.kt
  app/src/main/java/com/infomaniak/mail/di/RealmQualifiers.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1068 Fix `null` Mailbox after migration
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: bug

#1070 Message: Replace `fun isInTrash()` with `isTrashed: Boolean`, to uniformize with `isDraft` & `isSpam`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: optimization, quick

#1071 Fail-fast if Message is already in Folder
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: optimization, quick

#1072 UI for locked Mailbox in MailboxList
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/LockedMailboxBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SwitchMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/res/drawable-night/ic_invalid_mailbox.xml
  app/src/main/res/drawable/ic_invalid_mailbox.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1075 Enhance Sentry breadcrumbs
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization, quick

#1074 Optimize `unreadCountChip` closeIcon usage
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: optimization, quick

#1078 Move Signature Sentry to the right spot
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
Labels: bug, quick

#1081 Fix deeplink Draft's saving
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, quick

#1079 Only send ThemedActivity Sentry when there's an issue
  app/src/main/java/com/infomaniak/mail/ui/ThemedActivity.kt
Labels: optimization, quick

#1080 Update Notifications Sentry
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/standard/java/com/infomaniak/mail/GplayUtils.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: optimization, quick

#1082 Fix: `getDraft()` doesn't crash anymore
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, quick

#1086 feat: Asynchronous load and calculate folders diff
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
Labels: enhancement

#1085 Fix inject mailbox content
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/AttachmentController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/di/RealmDatabaseModule.kt
  app/src/main/java/com/infomaniak/mail/di/RealmQualifiers.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
Labels: bug

#1087 Fix mailbox switcher bug when only 1 mailbox
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
Labels: bug

#1088 fix: Reply a message doesn't autofill the fields
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
Labels: bug
