Repository Infomaniak/android-kMail, pull requests merged in 2023-03, with the labels that each got.

#654 Fix new message color
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/res/layout/activity_new_message.xml
  app/src/main/res/layout/item_contact.xml
  app/src/main/res/raw/custom_dark_mode_signature.css
  app/src/main/res/values/colors.xml
Labels: enhancement

#650 Add `searchResults` debounce before calling API
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: enhancement

#651 Save `recentSearches` after each new search
  app/src/main/java/com/infomaniak/mail/ui/main/search/RecentSearchAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: enhancement

#660 Correctly use `getLocalizedName()` instead of `name`
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
Labels: bug

#653 Remove nullability in SignatureController
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/SignaturesResult.kt
Labels: optimization

#661 Use localized strings for `notYetImplemented()`
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, dependent, quick

#662 Fix ugly background of Copy/Paste popup
  app/src/main/res/values/styles.xml
Labels: bug, quick

#647 Factorize `setClosingOnClick` listeners
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: optimization

#655 Update CreateFolder dialog
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/color/primary_button_background.xml
  app/src/main/res/layout/dialog_input.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#663 Split Body history from Message
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMessagesWorker.kt
Labels: feature

#667 Update Infomaniak kMail logo
  app/src/main/res/drawable-night/ic_logo_infomaniak_mail.xml
  app/src/main/res/drawable/ic_logo_infomaniak_mail.xml
Labels: quick

#664 Disable WebView recycling in Thread fragment
  app/src/main/res/layout/fragment_thread.xml
Labels: bug, quick

#658 Flush UI in Threads list
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/res/layout/item_thread_flush_folder_button.xml
Labels: feature

#659 Confirmation dialog when flushing
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: feature, quick

#657 API call when flushing a Folder
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: feature, quick

#668 Fix missing collapsable subject inside a thread
  app/src/main/res/layout/fragment_thread.xml
Labels: bug, quick

#669 Fix webview display inline attachment
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug, quick

#671 feat: Logout user token on logout of user
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: enhancement, quick

#672 Add missing quote descriptors
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: enhancement

#674 Use `context` instead of `getApplication()` in AndroidViewModels
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
Labels: optimization

#678 fix: Missing message when we split a message
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: bug, quick

#679 Update Threads list spacing
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/item_thread_date_separator.xml
Labels: enhancement

#676 Fix SearchHistory not being saved when entries are removed
  app/src/main/java/com/infomaniak/mail/ui/main/search/RecentSearchAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: bug, quick

#682 Deleting SearchResults from a newly added account caused an `IllegaleStateException`
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug, quick

#683 Remove unused variable
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: optimization, quick

#684 Remove `readAndArchive` swipe action
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#686 Make Body' `subBody` a String
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
Labels: enhancement

#685 fix: From a send intent it happens that an attachment is missing
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
Labels: bug, quick

#670 Show/hide quoted text in Message
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature

#687 Update thread density illustrations
  app/src/main/res/drawable-night/bg_list_density_compact.xml
  app/src/main/res/drawable-night/bg_list_density_default.xml
  app/src/main/res/drawable-night/bg_list_density_large.xml
  app/src/main/res/drawable/bg_list_density_compact.xml
  app/src/main/res/drawable/bg_list_density_default.xml
  app/src/main/res/drawable/bg_list_density_large.xml
Labels: quick

#701 Move SendMessage button down + Align Actions to the left
  app/src/main/res/layout/activity_new_message.xml
Labels: enhancement, quick

#700 Change back dark color of NewMessage composition
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageFragment.kt
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/raw/custom_dark_mode_signature.css
  app/src/main/res/values/colors.xml
Labels: quick

#699 Fix HTML tags in `text/plain` emails
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: bug, quick

#689 Multiselect UI logic
  app/src/main/java/com/infomaniak/mail/data/models/thread/SelectedThread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/MultiSelectionListener.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/views/BottomQuickActionBarView.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/menu/multiselection_menu.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#690 Multiselect UI
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/SimpleSettingView.kt
  app/src/main/res/drawable/ic_checkbox_unchecked.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/view_simple_setting.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#691 Multiselect Menu bottom sheet
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/models/thread/SelectedThread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/res/layout/bottom_sheet_multi_select.xml
  app/src/main/res/menu/main_actions_multi_select_menu.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#704 Remove `abstract currentClassName`
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: optimization

#692 Clean Multiselect code
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/main/res/layout/fragment_move.xml
Labels: optimization

#693 Update existing `Actions` codebase to handle multiple `Threads` at once
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
Labels: feature

#694 `Archive` API call for Multiselection
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: feature

#696 `Favorite/Unfavorite` API calls for Multiselection
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: feature

#697 `Seen/Unseen` API calls for Multiselection
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
Labels: feature

#695 `Delete` API call for Multiselection
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: feature

#698 `Move` API call for Multiselection
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#703 `Spam/Ham` API calls for Multiselection
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: feature

#706 Implement quick actions disabled state and fix crash with zero selected items
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/views/BottomQuickActionBarView.kt
  app/src/main/res/color/primary_color_disabled.xml
  app/src/main/res/values/styles.xml
Labels: bug

#707 Remove magic numbers when using `bottomQuickActionBarView`
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: optimization

#710 Protect from crash when multiselecting some unexisting Threads
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
Labels: bug

#709 Fix WebView's `backgroundColor` in dark mode for `text/plain` when displaying Message
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/res/layout/item_message.xml
Labels: bug

#716 Update Search EmptyState placeholder with the real one
  app/src/main/res/drawable-night/ic_empty_state_search.xml
  app/src/main/res/drawable/ic_empty_state_search.xml
  app/src/main/res/layout/fragment_search.xml
Labels: quick

#718 Fix Threads list start spacing due to new Multiselection specs
  app/src/main/res/layout/cardview_thread_item.xml
Labels: enhancement

#719 Fix CI for Matomo
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
Labels: bug, quick

#720 New header color
  app/src/main/res/color/header_color_light.xml
  app/src/main/res/values/colors.xml
Labels: quick

#577 Add missing Messages during Threads algo
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: bug

#714 Override Message `equals()`
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: optimization

#717 Add previous Message history when composing a new mail
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: feature

#712 Dismiss `loadingTimer` when `refreshThreads()` coroutine is cancelled
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug, quick

#726 Fix unread chip visibility when LiveData's value is null
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
Labels: bug, quick

#727 Fix mail bottom margin and margins of plain text
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/res/raw/add_padding.css
  app/src/main/res/raw/remove_margin.css
Labels: bug

#725 Add Onboarding System theme as `notYetImplemented()`
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/fragment_intro.xml
Labels: enhancement

#722 Add EmptyStates logic
  app/src/main/java/com/infomaniak/mail/ui/main/EmptyStateView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/res/drawable-night/ic_empty_state_folder.xml
  app/src/main/res/drawable-night/ic_empty_state_inbox.xml
  app/src/main/res/drawable-night/ic_empty_state_network.xml
  app/src/main/res/drawable-night/ic_empty_state_trash.xml
  app/src/main/res/drawable/ic_empty_state_folder.xml
  app/src/main/res/drawable/ic_empty_state_inbox.xml
  app/src/main/res/drawable/ic_empty_state_network.xml
  app/src/main/res/drawable/ic_empty_state_no_mail.xml
  app/src/main/res/drawable/ic_empty_state_trash.xml
  app/src/main/res/drawable/ic_no_network.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/view_empty_state.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#730 Do not change NavigationBar `color` for API < 27
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug, quick

#731 Update `colorOnPrimary` according to specs
  app/src/main/res/color/on_primary_color_disabled.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#732 fix: Some accessing an object invalidated or deleted from realm
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
Labels: bug

#734 Remove 1 useless RealmQuery in Threads algo
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: optimization, quick

#737 Add confirmation dialog when multi-deleting in Draft, Spam & Trash folders
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#735 Correctly execute Draft's action if the Draft has become obsolete while editing it
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: bug, rebase

#745 Remove useless type specification in `getApplication()`
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
Labels: optimization

#740 Update Search's folders dropdown design with a divider and "All folders" icon
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_all_folders.xml
  app/src/main/res/layout/item_divider_horizontal.xml
Labels: enhancement

#747 Update MergedContacts logic to display Avatars by email
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: enhancement

#749 Mail detailed informations UI fixes
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/res/layout/item_detailed_contact.xml
  app/src/main/res/layout/item_message.xml
Labels: bug

#751 Migrate to Realm Kotlin 1.7.0 + Java 11
  app/build.gradle
  build.gradle
  settings.gradle
Labels: enhancement

#750 Don't reset `unreadCount` filter when coming back on Threads list
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: feature

#752 Remove Thread from list when reading it while Unseen filter is ON
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: feature, quick

#744 Add additional Matomo trackers
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement, quick

#755 `UpdatedAt` now always has a text
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, quick

#756 Fix Realm `afterUpdateAdapter`
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
Labels: bug

#754 Filter with Folder doesn't accept to filter Folders in succession
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
Labels: bug

#758 Empty States are now correctly shown & hidden
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug

#761 Add attachment downloading if no application can open it
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: feature, quick

#748 Split Outlook quote + Improve split blockquote logic
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: bug, enhancement

#762 Add German, Italian and Spanish translations
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#763 Clean Strings `<resources>` tag
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: optimization, quick

#765 When fetching `activities`, delete old Messages before adding new ones
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: bug

#766 Update strings for new Onboarding wording + Fix CI crash in Spanish strings
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, optimization, quick

#768 Fix new Attachments overriding old ones
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#770 feat: New create account url
  app/build.gradle
Labels: enhancement, quick

#771 Fix Signature being cut off
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/ContactChipAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
  app/src/main/res/layout/chip_contact.xml
  app/src/main/res/layout/view_recipient_field.xml
Labels: bug

#774 Slightly decrease vertical spacing between chips to match spacing with top divider
  app/src/main/res/layout/chip_contact.xml
  app/src/main/res/layout/view_recipient_field.xml
Labels: quick

#769 Add duration to animated Splash icon on Android 12, so it's displayed again
  app/src/main/res/values-v31/themes.xml
Labels: bug

#775 Handle Draft actions API errors
  app/src/main/java/com/infomaniak/mail/utils/Exceptions.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, enhancement, quick

#776 Block adding more recipient with a snackbar if limit has been reached
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/RecipientFieldView.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, quick

#782 Use `?attr/isLightTheme` for `windowLightStatusBar` item
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/values-night-v31/themes.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: optimization, quick

#785 Replace `?.let { …(it) }` with `?.let(::…)` when possible
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedViewModelUtils.kt
Labels: optimization, quick

#784 Fix orphan Messages when Threads algo was cut in the middle
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug, quick

#786 feat: Create sentry release for each new tag
  .github/workflows/sentry-release.yml
Labels: enhancement

#787 Make `searchQuery` LiveData instead of StateFlow to allow to trigger it again
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: bug

#788 Use `ThreadFilter.FOLDER` instead of checking `folder` nullability
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
Labels: optimization

#791 Fixes SENTRY-109662 (NPE in MainViewModel `forceRefreshMailboxesAndFolders()`)
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug, quick

#797 Add dialog when trying to send an email without subject
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#795 fix: Sentry 112211 - Serializer for class 'Any' is not found
  app/src/main/java/com/infomaniak/mail/utils/Exceptions.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#794 Revert "Remove dividers between swipe action setting choices"
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
Labels: feature

#792 Save `query` in History only if keyboard button pressed or Thread clicked
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: feature

#803 Support system theme in the app except for onboarding
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/AccentColorSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioButtonView.kt
  app/src/main/res/color-night/onboarding_secondary_background.xml
  app/src/main/res/color/color_primary_transparent.xml
  app/src/main/res/color/onboarding_secondary_background.xml
  app/src/main/res/color/text_color_highlight.xml
  app/src/main/res/drawable/ic_accent_blue.xml
  app/src/main/res/drawable/ic_accent_pink.xml
  app/src/main/res/layout/fragment_accent_color_setting.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature

#804 Support system theme in the onboarding except for Lottie
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: feature

#805 Simplify, clean and fix the way Lottie animations are colored to be able to work with it
  app/src/main/java/com/infomaniak/mail/ui/login/IlluColors.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/NoMailboxActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#809 Fix expeditor names if `isMe()` when there are more than one expeditor in a thread
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: bug, quick

#812 fix: The `swipeRefresh` layout lags too much in Threads list
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
Labels: enhancement

#807 Update sending email without subject
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/main/newMessage/NewMessageActivity.kt
Labels: enhancement

#813 Update `gradle-wrapper.properties`
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#815 fix: update android ci to jdk17 + update actions
  .github/workflows/android.yml
Labels: bug
