Repository Infomaniak/android-kMail, pull requests merged in 2024-12, with the labels that each got.

#2124 refactor: Remove all `.removeFirst()` & `.removeLast()`
  app/src/main/java/com/infomaniak/mail/data/api/FlatteningSubBodiesSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/RecentSearchAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: quick

#2087 fix: Don't show the contact if the email is incorrect
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
Labels: bug, quick

#2127 feat: Add APP_EMAIL and DEFAULT category to the main activity in the manifest
  app/src/main/AndroidManifest.xml
Labels: enhancement
