Repository Infomaniak/android-kMail, pull requests merged in 2024-06, with the labels that each got.

#1885 Fix reliability issues
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: bug

#1891 The default value of `isThemeTheSame` should be `true`, and not `false`
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: optimization

#1887 Replace this throw expression with error("").
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
Labels: optimization

#1888 Make this interface functional or replace it with a function type.
  app/src/main/java/com/infomaniak/mail/ui/main/settings/OnCheckListener.kt
Labels: optimization

#1867 Add banner to tell the user the webview needs to be updated
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/BannerWithActionView.kt
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_banner_with_action_view.xml
  app/src/main/res/layout/view_banner_with_action.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1890 Refactor the code to eliminate this nested "when".
  app/src/main/java/com/infomaniak/mail/utils/ConfettiUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/LoginUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: optimization

#1889 Remove mutable parameter.
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
Labels: optimization

#1892 Correct german wording
  app/src/main/res/values-de/strings.xml
Labels: quick

#1894 Temp fix attachments
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: enhancement

#1896 Fix calendar event canceled detection
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEvent.kt
  app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEventResponse.kt
  app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt
Labels: enhancement

#1880 Place information icon of external banner to the left of the banner
  app/src/main/res/layout/fragment_new_message.xml
Labels: enhancement, quick

#1876 Delete Thread in Realm if it's empty and we're trying to display it in ThreadsList
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapterCallback.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug

#1903 Remove Sentry about "No new Message" notification
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: optimization, quick

#1900 Fix natural auto advance thread mode
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: bug

#1886 Split this XXX characters long line (which is greater than 130 authorized).
  HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/BodyCleaner.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/EmailContextualMenuAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
Labels: optimization

#1907 fix: Sometimes gradle throw an OOM
  gradle.properties
Labels: enhancement

#1910 Do not pass list of message when it only contains one message
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#1909 Exceptions in executeWithTimeoutOrDefault are now correctly handled
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: bug, quick

#1914 Rename & move packages
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/MailboxListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerDropdownView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/RestoreEmailsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/SimpleSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/move/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/move/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/move/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesFragment.kt
  app/src/main/java/com/infomaniak/mail/views/BottomSheetScaffoldingView.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bottom_sheet_restore_emails.xml
  app/src/main/res/layout/fragment_accent_color_setting.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_ai_engine_setting.xml
  app/src/main/res/layout/fragment_attach_mailbox.xml
  app/src/main/res/layout/fragment_auto_advance_settings.xml
  app/src/main/res/layout/fragment_cancel_delay_setting.xml
  app/src/main/res/layout/fragment_data_management_matomo_setting.xml
  app/src/main/res/layout/fragment_data_management_sentry_setting.xml
  app/src/main/res/layout/fragment_data_management_settings.xml
  app/src/main/res/layout/fragment_external_content_setting.xml
  app/src/main/res/layout/fragment_forward_mails_setting.xml
  app/src/main/res/layout/fragment_invalid_password.xml
  app/src/main/res/layout/fragment_mailbox_settings.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_move.xml
  app/src/main/res/layout/fragment_send_settings.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_signature_setting.xml
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
  app/src/main/res/layout/fragment_swipe_actions_settings.xml
  app/src/main/res/layout/fragment_switch_user.xml
  app/src/main/res/layout/fragment_theme_setting.xml
  app/src/main/res/layout/fragment_thread_list_density_setting.xml
  app/src/main/res/layout/fragment_thread_mode_setting.xml
  app/src/main/res/layout/item_menu_drawer_folder.xml
  app/src/main/res/layout/item_menu_drawer_mailbox.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: optimization, quick

#1918 Do not log FCM exception SERVICE_NOT_AVAILABLE
  app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt
Labels: enhancement, quick

#1921 Rename some strings used by the information block
  app/src/main/res/layout/fragment_no_valid_mailboxes.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, quick

#1924 Remove `reason` in `sendFailedNotification()` to dissociate Sentries
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: optimization

#1925 Add Sentry to check if the API can send us a Message from another Folder
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug

#1928 Fix NPE when trying to get local contact email
  app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
Labels: bug

#1929 Move the access of `uiAttachments` liveData to `updateDraftAttachmentsFromLiveData()` parameters
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: optimization

#1930 Simplify Attachment IDs usage
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/DraftExtensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement, rebase

#1927 Delete Drafts orphans after sending the Sentry about them
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#1932 Simplify enabling algorithmic darkening on webviews
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: enhancement, quick

#1931 Add last modified date in URI when sending attachment to kDrive
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
Labels: enhancement

#1913 Add Bimi feature
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/Bimi.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/di/ApplicationModule.kt
  app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/drawable/ic_certified.xml
  app/src/main/res/layout/bottom_sheet_detailed_contact.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/view_avatar_name_email.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#1935 Protect against empty isThemeTheSameMap and add Sentry to better understand the issue
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: bug

#1938 Fix external banner text color in dark mode
  app/src/main/res/layout/fragment_new_message.xml
Labels: bug, quick

#1940 Reduce Bimi priority (it should only be displayed if we couldn't find an avatar)
  app/src/main/java/com/infomaniak/mail/data/models/Bimi.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: enhancement

#1937 Support a second different core copyright for core files
  .idea/copyright/Core_copyright.xml
  .idea/copyright/Infomaniak_Open_Source.xml
  .idea/copyright/profiles_settings.xml
  .idea/scopes/Core_project_files.xml
Labels: enhancement

#1942 Remove useless space
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: quick

#1944 Fix Bimi when recycling
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: bug

#1945 Add auto advance icon
  app/src/main/res/drawable/ic_auto_advance_arrow_down.xml
  app/src/main/res/drawable/ic_auto_advance_arrow_up.xml
  app/src/main/res/drawable/ic_auto_advance_last_action.xml
  app/src/main/res/drawable/ic_auto_advance_list_conversation.xml
  app/src/main/res/layout/fragment_auto_advance_settings.xml
Labels: enhancement
