Repository Infomaniak/android-kMail, pull requests merged in 2024-10, with the labels that each got.

#2061 Fix using backspace to delete recipient on API 34+
  app/src/main/java/com/infomaniak/mail/ui/newMessage/BackspaceAwareChip.kt
  app/src/main/res/layout/chip_contact.xml
Labels: bug

#2064 Prioritize api contacts avatar over phone contacts avatar
  app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
Labels: enhancement, quick

#2062 Fix ripple of the move fragment
  app/src/main/res/layout/fragment_move.xml
  app/src/main/res/values/dimens.xml
Labels: bug

#2016 Execute actions right away instead of waiting for API call result
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: feature

#2066 Revert "Prioritize api contacts avatar over phone contacts avatar"
  app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
Labels: quick

#2067 Give priority to autocompleted api contacts over phone contacts
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/ContactUtils.kt
Labels: enhancement

#2072 Set avatar background color to white so transparent BIMIs are displayed correctly
  app/src/main/res/layout/view_avatar.xml
Labels: bug, quick

#2078 chore(Sentry): Remove sentry of _uploadStatus that is useless
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
Labels: enhancement, quick

#2081 fix: DownloadAttachmentProgressFragment lifecycle crash
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
Labels: bug, quick

#2082 Truncate messages at 104_448 to prevent OOM error on SplitBody
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: bug, quick

#2086 Add some sentry to better understand message display improvements that still leave some overscroll
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewVersionUtils.kt
Labels: bug, enhancement, quick
