Repository Infomaniak/android-kMail, pull requests merged in 2024-04, with the labels that each got.

#1781 Clean code
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactChipAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: optimization

#1794 Only log if we are at the last Fibonacci or at ABORT_MISSION
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization

#1795 Fix race condition when the last Message of a Thread is deleted while the Thread is open
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: bug

#1793 Fix "Load more" button appearing too often
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug

#1797 Add a tag to have Sentry stats on ApiErrorException
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1803 Remove useless sentries
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug, enhancement

#1804 Fix a crash when an Email's body in a Notification had too many characters
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: bug

#1802 Fix MainApp lint warning
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#1783 D1: Prepare to use LiveData instead of Draft model for UI
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: feature

#1785 D2: `subject` field now uses its own LiveData
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/res/navigation/new_message_navigation.xml
Labels: feature

#1788 D5: `signature` field now uses its own LiveData
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: feature

#1789 D6: `from` field now uses its own LiveData
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
Labels: feature

#1790 D7: `attachments` field now uses its own LiveData
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: feature

#1791 D8: `recipients` fields now use their own LiveData
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: feature

#1810 Update Signatures Sentry
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: optimization

#1811 Handle Sentry about receiving too much Users
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: bug

#1800 D10: Simplify Draft initialization
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SignatureUtils.kt
Labels: optimization, dependent

#1812 Change mail periodic refresh condition & dismiss notifications of already read messages
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
Labels: enhancement, rebase

#1817 Simplify Draft initialization
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SignatureUtils.kt
Labels: optimization

#1813 Fix UI not updating when "Don't keep activities" is enabled
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
Labels: bug

#1822 Sort & rename Settings in `main_navigation`
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: optimization, dependent

#1821 Reformat code
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/ui/login/IlluColors.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsMailboxesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: optimization

#1815 Also save Draft when going on background or FilePicker or IA
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: feature

#1824 Fix Matomo and Sentry features optout
  app/src/main/java/com/infomaniak/mail/ui/main/settings/privacy/DataManagementMatomoSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/privacy/DataManagementSentrySettingFragment.kt
  app/src/main/res/drawable-night/illustration_data_management_paper.xml
  app/src/main/res/drawable/illustration_data_management_paper.xml
  app/src/main/res/layout/fragment_data_management_matomo_setting.xml
  app/src/main/res/layout/fragment_data_management_sentry_setting.xml
  app/src/main/res/layout/fragment_data_management_settings.xml
Labels: enhancement

#1831 Dismiss the group notification if we dismissed the last notification
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: bug

#1833 Always delete Draft if the API call to save/send fails
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug
