Repository Infomaniak/android-kMail, pull requests merged in 2024-07, with the labels that each got.

#1946 Feature flag BIMI
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/models/Bimi.kt
  app/src/main/java/com/infomaniak/mail/data/models/FeatureFlag.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/AvatarMergedContactData.kt
Labels: feature

#1950 Fix bimi out of place certification
  app/src/main/res/layout/view_avatar_name_email.xml
Labels: bug

#1951 Remove nesting of bodies when sanitizing html
  HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/BodyCleaner.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: bug, enhancement

#1954 Add share mail link feature
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/models/ShareThread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/res/drawable/ic_email_action_share.xml
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1963 Rename patchnotes versions for FDroid
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  fastlane/metadata/android/en-US/changelogs/1_03_002_01.txt
  fastlane/metadata/android/en-US/changelogs/1_03_003_01.txt
  fastlane/metadata/android/en-US/changelogs/1_03_004_01.txt
  fastlane/metadata/android/en-US/changelogs/1_03_005_01.txt
  fastlane/metadata/android/fr/changelogs/1_03_002_01.txt
  fastlane/metadata/android/fr/changelogs/1_03_003_01.txt
  fastlane/metadata/android/fr/changelogs/1_03_004_01.txt
  fastlane/metadata/android/fr/changelogs/1_03_005_01.txt
Labels: bug

#1964 chores(Sentry): Remove useless Sentry
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
Labels: quick

#1939 Add forward and reply icons on threads
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/res/drawable/ic_email_action_forward_filled.xml
  app/src/main/res/drawable/ic_email_action_reply_filled.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1968 Fix/sonar cloud issues
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IlluColors.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/send/ForwardMailsSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: bug

#1969 Fix cut name
  app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/res/layout/view_avatar_name_email.xml
Labels: bug

#1971 Factorize reset of Folder's content
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: optimization

#1979 Update Sentry about Failed notifications
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: optimization

#1967 Fix uncatched NPE in RecipientFieldView
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
Labels: quick

#1984 Fix the Editor toolbar displayed under the keyboard
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
Labels: bug, quick

#1980 Use single name import instead of wildcard
  .idea/codeStyles/Project.xml
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/FlatteningSubBodiesSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/InputAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/CoroutineScopeUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/MailDateFormatUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/main/res/navigation/main_navigation.xml
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
Labels: enhancement, quick

#1982 Add more breadcrumbs to better understand Attachments issues
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/DraftUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: optimization
