Repository Infomaniak/android-kMail, pull requests merged in 2024-09, with the labels that each got.

#2030 Add more info about supposed empty Thread in Sentry
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug, quick

#2031 Add more info about supposed orphan Drafts in Sentry
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, quick

#2025 Make sure we use the up-to-date version of Folder in RefreshController
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: bug, quick

#2026 Calm down Realm breadcrumbs
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryRealmLogger.kt
Labels: optimization

#2027 Clean code
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
Labels: quick

#2033 Fix indexOutOfBounds exception
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerAdapter.kt
Labels: bug

#2036 Catch exception in uploadStatus getter and add info for sentry
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug, quick

#2034 Remove useless sentry
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
Labels: enhancement, quick

#2038 Simplify `.joinToString()` usage
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryRealmLogger.kt
Labels: quick

#2037 Remove deleteToken sentry
  app/src/main/java/com/infomaniak/mail/utils/LoginUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt
Labels: enhancement, quick

#2053 Fix animated toolbar crash
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: bug

#2052 Remove now unused DraftActionsWorker setProgress
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement, quick

#2055 Delete draft that cannot ever be sent because of corrupted attachments
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug, quick
