Repository Infomaniak/android-kMail, pull requests merged in 2024-08, with the labels that each got.

#1990 Log jsoup parsing ram usage
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
  app/src/main/java/com/infomaniak/mail/utils/JsoupParserUtil.kt
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: bug

#1988 Enhance `addAttachmentsBreadcrumb()` code readability
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: optimization

#1991 Add memory usage logs around a Jsoup.parse that was missed
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
Labels: enhancement, quick

#1986 Add SentryLog when mailboxId uses the default value for configuration
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
Labels: bug, quick

#1958 Replace current editor with rich html editor
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/BodyContentPayload.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/EditorContentManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/utils/SignatureUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/raw/editor_style.css
  gradle/libs.versions.toml
Labels: feature

#1959 Update caret color of the rich html editor
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlFormatter.kt
  app/src/main/java/com/infomaniak/mail/utils/SignatureUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/WebViewUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/res/raw/editor_style.css
Labels: enhancement

#1992 Remove associated inline attachements when removing quote
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/HtmlUtils.kt
Labels: bug, enhancement

#2002 Bump `MAILBOX_CONTENT_SCHEMA_VERSION` so it runs again when upgrading from v1.4.3
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
Labels: bug

#1999 fix: App crashes because of AvatarView
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: bug, quick

#2001 Remove Messages from Folders in MenuDrawer
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/move/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: optimization

#2003 Fix missing selection indicator handles when the selected line is on the last line of the rich html editor
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/raw/editor_style.css
Labels: quick

#2008 Put back wildcards
  .idea/codeStyles/Project.xml
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/FlatteningSubBodiesSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/InputAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/HeaderItemDecoration.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/MenuDrawerAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/RestoreEmailsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/move/MoveViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/AccentColorSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/ThemeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/ThreadListDensitySettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AttachMailboxFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/CoroutineScopeUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/MailDateFormatUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/SyncMailboxesWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
Labels: user feedback, quick

#2007 Bump Libs
  gradle/libs.versions.toml
Labels: optimization

#1996 Add toolbar formatting options to the new rich html editor
  app/src/main/java/com/infomaniak/mail/ui/newMessage/InsertLinkDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
  app/src/main/res/color/editor_button_background.xml
  app/src/main/res/color/icon_button_disabled.xml
  app/src/main/res/layout/dialog_insert_link.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#2012 Fix infinite refresh loading of Threads when switching Account/Mailbox
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: bug

#2009 Clean Realm Lists & Sets types in Models
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/SwissTransferContainer.kt
  app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEvent.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/SubBody.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: optimization

#2005 Variables renaming
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: optimization

#2006 Optimize `getThreads()` query when executing action on Threads/Messages
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
Labels: optimization

#2000 Batch API calls when there is more than 1000 UIDs
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/SnackbarManager.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: bug

#1993 Allow keyboard navigation
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFolderAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/MailboxSettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/privacy/DataManagementSettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_ai_engine_choice.xml
  app/src/main/res/layout/fragment_ai_prompt.xml
  app/src/main/res/layout/fragment_ai_proposition.xml
  app/src/main/res/layout/fragment_data_management_settings.xml
  app/src/main/res/layout/fragment_mailbox_settings.xml
  app/src/main/res/layout/fragment_move.xml
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_swipe_actions_settings.xml
  app/src/main/res/layout/fragment_sync_configure.xml
  app/src/main/res/layout/fragment_sync_onboarding.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/view_simple_setting.xml
  app/src/main/res/values/styles.xml
Labels: feature

#2019 Can now report display problems (staff only)
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: feature

#1970 Fetch Messages by Date (instead of UID) when going through Folder's history
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/getMessages/ActivitiesResult.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: enhancement

#2023 Clean code
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/utils/DraftUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/BaseCoroutineWorker.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/RegisterUserDeviceWorker.kt
Labels: quick

#2024 Update Sentry scope usage
  app/src/main/java/com/infomaniak/mail/data/api/UnwrappingJsonListSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/receivers/NotificationActionsReceiver.kt
  app/src/main/java/com/infomaniak/mail/ui/BaseActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ConfettiUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/standard/java/com/infomaniak/mail/StandardPlayServicesUtils.kt
Labels: optimization

#2028 fix: Clean gradle cache form ci
  .github/workflows/android.yml
Labels: quick
