Repository Infomaniak/android-kMail, pull requests merged in 2024-05, with the labels that each got.

#1832 Only save Draft when adding Attachment
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
Labels: optimization

#1826 Draft revamp
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/BaseActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/DescriptionAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/DiscoveryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/InvalidPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/onboarding/PermissionsOnboardingPagerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactChipAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/noValidMailboxes/NoValidMailboxesFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ExternalUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/utils/SignatureUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/view_recipient_field.xml
  app/src/main/res/navigation/new_message_navigation.xml
  app/src/main/res/values/colors.xml
Labels: bug, enhancement, feature, optimization, quick

#1829 Remove personal info from sentry
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1841 Add Sentry breadcrumbs about "Already existing message"
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization

#1825 Shortcut long press
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/res/drawable/ic_shortcut_help_foreground.xml
  app/src/main/res/drawable/ic_shortcut_new_message_foreground.xml
  app/src/main/res/drawable/ic_shortcut_search_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_shortcut_help.xml
  app/src/main/res/mipmap-anydpi-v26/ic_shortcut_help_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_shortcut_new_message.xml
  app/src/main/res/mipmap-anydpi-v26/ic_shortcut_new_message_round.xml
  app/src/main/res/mipmap-anydpi-v26/ic_shortcut_search.xml
  app/src/main/res/mipmap-anydpi-v26/ic_shortcut_search_round.xml
  app/src/main/res/mipmap-hdpi/ic_shortcut_help.webp
  app/src/main/res/mipmap-hdpi/ic_shortcut_help_round.webp
  app/src/main/res/mipmap-hdpi/ic_shortcut_new_message.webp
  app/src/main/res/mipmap-hdpi/ic_shortcut_new_message_round.webp
  app/src/main/res/mipmap-hdpi/ic_shortcut_search.webp
  app/src/main/res/mipmap-hdpi/ic_shortcut_search_round.webp
  app/src/main/res/mipmap-mdpi/ic_shortcut_help.webp
  app/src/main/res/mipmap-mdpi/ic_shortcut_help_round.webp
  app/src/main/res/mipmap-mdpi/ic_shortcut_new_message.webp
  app/src/main/res/mipmap-mdpi/ic_shortcut_new_message_round.webp
  app/src/main/res/mipmap-mdpi/ic_shortcut_search.webp
  app/src/main/res/mipmap-mdpi/ic_shortcut_search_round.webp
  app/src/main/res/mipmap-xhdpi/ic_shortcut_help.webp
  app/src/main/res/mipmap-xhdpi/ic_shortcut_help_round.webp
  app/src/main/res/mipmap-xhdpi/ic_shortcut_new_message.webp
  app/src/main/res/mipmap-xhdpi/ic_shortcut_new_message_round.webp
  app/src/main/res/mipmap-xhdpi/ic_shortcut_search.webp
  app/src/main/res/mipmap-xhdpi/ic_shortcut_search_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_shortcut_help.webp
  app/src/main/res/mipmap-xxhdpi/ic_shortcut_help_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_shortcut_new_message.webp
  app/src/main/res/mipmap-xxhdpi/ic_shortcut_new_message_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_shortcut_search.webp
  app/src/main/res/mipmap-xxhdpi/ic_shortcut_search_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_shortcut_help.webp
  app/src/main/res/mipmap-xxxhdpi/ic_shortcut_help_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_shortcut_new_message.webp
  app/src/main/res/mipmap-xxxhdpi/ic_shortcut_new_message_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_shortcut_search.webp
  app/src/main/res/mipmap-xxxhdpi/ic_shortcut_search_round.webp
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/xml/shortcuts.xml
Labels: feature, rebase

#1835 Detail attachement bug to sentry
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1846 Fix clickListener not being recycled correctly if thread doesn't have sender
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: bug

#1845 Don't display Delete confirmation popup for Drafts
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: enhancement

#1848 Add some info for thread with several parent folders
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: enhancement, quick

#1850 Put ThreadList adapters initialisations together
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: enhancement

#1856 Support `mailTo` from `Intent.Send`
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: enhancement

#1844 Update Signature API and handle nullable signature
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/SignatureController.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/SignaturesResult.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1853 Don't log NetworkException in Sentry
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
Labels: optimization, quick

#1857 Remove useless Sentry scope
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: optimization, quick

#1854 Fix disappearing multi-select on a single Thread when selecting the "More" action
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ReplyBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: enhancement

#1858 Use `ConcurrentHashMap` instead of `mutableMapOf` for `notificationsByMailboxId` to fix OOB
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
Labels: bug, quick

#1860 Remove comment about old "Should display threads is true" bug
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug

#1843 Auto-advance
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapterCallback.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/AutoAdvanceSettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/SignatureAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/res/layout/fragment_auto_advance_settings.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1864 Chromebook : various improvements
  app/src/main/AndroidManifest.xml
Labels: enhancement

#1872 Increase debounce to avoid being spammed with notifications sound and vibration
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
Labels: enhancement

#1874 Move some Realm functions to Controllers' companions
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/FolderController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
Labels: optimization

#1881 fix: KotlinNullPointerException form Base
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/BaseAlertDialog.kt
Labels: bug

#1883 Fix NPE when getting email in `getDummySignature`
  app/src/main/java/com/infomaniak/mail/data/models/signature/Signature.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: bug
