Repository Infomaniak/android-kMail, pull requests merged in 2024-03, with the labels that each got.

#1713 Only display Loader for current Folder
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: enhancement

#1719 Allow to unfavorite Drafts
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
Labels: bug, quick

#1722 Cleaning
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/ui/login/IntroViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
  app/src/test/java/com/infomaniak/mail/AppVersionCheckingTest.kt
Labels: optimization, quick

#1723 Fix print feature not working on SuperCollapsedBlock Message
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: bug

#1730 New CI
  .github/workflows/android.yml
Labels: optimization

#1718 Restore Thread state when coming back
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapterState.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: feature

#1731 Optimize opening of Thread to handle both ThreadFragment & PrintFragment
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/res/navigation/main_navigation.xml
Labels: optimization

#1725 Fix print not working for empty subject
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/PrintHeaderUtils.kt
Labels: bug, quick

#1728 Clean code before optimizing ThreadState handling
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/AttendeesBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: optimization

#1729 Use a class to store Thread state
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapterState.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadState.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: optimization

#1732 Swap `with(binding) { … }` with `with(threadViewModel) { … }`
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: optimization, quick

#1733 Opening a Thread now correctly marks it as read
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadState.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: bug

#1738 Only add myself once in Thread expeditors UI
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
Labels: bug

#1746 Move the ExternalContent setting to the correct Settings category
  app/src/main/res/layout/fragment_settings.xml
Labels: enhancement, quick

#1745 Format enums
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/FeatureFlag.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
  app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt
Labels: enhancement

#1742 Add `!isBooting` check before sending NoThreads Sentry
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: bug

#1743 Add Sentries to try to understand what's happening
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryDebug.kt
Labels: bug

#1656 Use `externalMailInfo` API call instead of `mailboxes` one to get ExternalMail info
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/Mailbox.kt
  app/src/main/java/com/infomaniak/mail/data/models/mailbox/MailboxExternalMailInfo.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/SubjectFormatter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/utils/ExternalUtils.kt
Labels: feature

#1735 UI now correctly updates when marking Thread as seen
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadState.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
Labels: bug

#1747 Small optimisation of duration in RefreshThreads algo
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DelayApiCallManager.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: optimization

#1758 fix: MenuDrawer throw an IllegalStateException
  app/src/main/java/com/infomaniak/mail/ui/main/menu/FolderAdapter.kt
Labels: bug

#1755 fix: Observe folders throw a Realm IllegalStateException
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
Labels: bug

#1757 In-App review in kMail
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/di/ActivityModule.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: enhancement

#1769 Trigger the CI all the time, for all PRs
  .github/workflows/android.yml
Labels: optimization

#1753 fix: MessageWebviewClient throw an IllegalStateException [RLM_ERR_INVALIDATED_OBJECT]
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
Labels: bug

#1748 Subscribe to a Mailbox's notifications when opening given Mailbox
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/FetchMessagesManager.kt
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: optimization

#1760 Format code before Draft revamp
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/AiDiscoveryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: optimization

#1762 Move code before Draft revamp
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
Labels: optimization

#1772 Remove checkbox in AI dialog
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/res/layout/dialog_ai_replace_content.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1773 Handle some SonarCloud issues
  HtmlCleaner/src/main/java/com/infomaniak/html/cleaner/HeadCleaner.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: optimization

#1774 Remove intelligent Mailbox related code
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/res/layout/item_thread_see_all_button.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: optimization

#1777 Add Signature into correct Draft object when `REPLY` or `REPLY_ALL`
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: bug

#1779 Remove unused sentry
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: quick

#1780 Add sentry log to understand issue #3276
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: quick

#1764 Save Draft in Realm when leaving NewMessage screen
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: feature

#1766 Allow to send multiple times the same Attachment + Correctly delete Attachments files
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/draft/Draft.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageWebViewClient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#1767 Correctly trigger Chevron visibility updates
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
Labels: bug

#1768 Hide Chevron until Draft loading is finished
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/res/layout/view_recipient_field.xml
Labels: bug

#1778 Remove side effects when using Draft object of NewMessageVM
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageExternalsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/ExternalUtils.kt
Labels: enhancement

#1784 Remove wrongly added Signature & Quote from Draft snapshot
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: bug
