Repository Infomaniak/android-kMail, pull requests merged in 2024-02, with the labels that each got.

#1675 Do not display bottomsheet if user already went by himself in onBoarding
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt
Labels: enhancement

#1681 Clean Illustrations
  app/src/main/res/drawable-night/illustration_discover_sync.xml
  app/src/main/res/drawable/ic_checkbox_unchecked.xml
  app/src/main/res/drawable/ic_external_information.xml
  app/src/main/res/drawable/illustration_discover_sync.xml
Labels: enhancement

#1666 Implement "Add to calendar" button
  app/src/main/java/com/infomaniak/mail/data/models/Attachment.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/utils/AttachmentIntentUtils.kt
Labels: feature

#1670 Fix margins around items inside a thread
  app/src/main/res/layout/item_message.xml
Labels: quick

#1679 Add possibility to reply to calendar events
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/calendar/Attendee.kt
  app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEvent.kt
  app/src/main/java/com/infomaniak/mail/data/models/calendar/CalendarEventResponse.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt
  app/src/test/java/com/infomaniak/mail/ExampleUnitTest.kt
  gradle/libs.versions.toml
Labels: feature, rebase

#1680 Calendar event matomo
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/models/calendar/Attendee.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
Labels: feature, rebase

#1686 Fix sorting by date in local search
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug, quick

#1685 Fix Search with Attachment filter
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
Labels: bug, quick

#1689 Fix the CI because of invalid strings
  app/src/main/res/values-fr/strings.xml
Labels: bug, enhancement, quick

#1650 Fix wrong SystemBars colors
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/NewAccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/AccentColorSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ExternalContentSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ThemeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadListDensitySettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ThreadModeSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/MailboxSettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/AiEngineSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/swipe/SwipeActionsSettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiEngineChoiceFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageManager.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncConfigureFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/navigation/login_navigation.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: bug

#1672 Lock MenuDrawer in ThreadFragment
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: bug

#1692 Fix search keyboard still being opened when entering a thread
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
Labels: bug, quick

#1687 Directly open Attachment when clicking on it
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/utils/AttachmentIntentUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/res/layout/item_attachment.xml
Labels: enhancement

#1688 Move all navigation extensions to own file
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/NavigationExtensions.kt
Labels: enhancement, quick

#1677 Make sure ThreadFragment is displayed after rotation
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
Labels: bug

#1693 Update AI loader to be more visible
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/res/drawable/ai_proposition_loader_gradient.xml
  app/src/main/res/layout/fragment_ai_proposition.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1701 Fix wrong Folder ID in Search Messages
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
Labels: bug

#1702 Deactivate multiselect if we don't have any selected mail
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
Labels: feature

#1704 Truncate Message' Subject if it's longer than 998 characters
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: bug

#1700 Ignore defaults avatars coming from the API for the User profile
  app/src/main/java/com/infomaniak/mail/ui/login/LoginActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/AccountUtils.kt
Labels: feature, quick

#1706 Fix Messages blink by removing SlidingPaneLayout
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/main/NoAnimSlidingPaneLayout.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/values-sw600dp-w840dp/constants.xml
  app/src/main/res/values-sw600dp/constants.xml
  app/src/main/res/values/constants.xml
  app/src/main/res/values/dimens.xml
  gradle/libs.versions.toml
Labels: bug, enhancement, optimization

#1710 Remove Sentry about negative Quota
  app/src/main/java/com/infomaniak/mail/data/models/Quotas.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
Labels: optimization, quick

#1711 Simplify MenuDrawer container usage
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: optimization, quick

#1684 Add SuperCollapsedBlock
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/AttendeesBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/utils/SimpleIconPopupMenu.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/res/layout/item_super_collapsed_block.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#1714 Simplify error-prone usage of `canRefreshThreads`
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement

#1717 Fix webview min height and add reply/forward new line
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
  app/src/main/res/layout/item_message.xml
Labels: enhancement, quick

#1720 Stop detecting outlook blockquotes
  app/src/main/java/com/infomaniak/mail/utils/MessageBodyUtils.kt
Labels: bug, quick

#1715 Remove duplicated Draft folder refresh
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: optimization
