Repository Infomaniak/android-kMail, pull requests merged in 2024-01, with the labels that each got.

#1617 Fix in app update
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/workers/AppUpdateWorker.kt
Labels: bug

#1618 Change surface color to new Material Tonal color API
  app/src/main/res/values/styles.xml
Labels: enhancement

#1613 T22: Progressively update statusBar & navigationBar colors when sliding pane
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
Labels: feature

#1615 Update the default font to display emails to Helvetica and remove text/plain unique font
  app/src/main/res/raw/style.css
Labels: quick

#1614 Simplify and lower coupling of updating AvatarView avatars
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/AvatarMergedContactData.kt
Labels: enhancement

#1620 Change values() to entries after kotlin 1.9
  app/src/main/java/com/infomaniak/mail/ui/main/settings/ItemSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt
  app/src/main/java/com/infomaniak/mail/views/itemViews/DecoratedItemView.kt
Labels: enhancement

#1623 Add missing Matomo
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/DiscoveryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/UpdateAvailableBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement

#1629 Make MenuDrawer dropdowns status ISO with iOS
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
Labels: feature

#1628 Remove `subFolders` animations in MenuDrawer
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuFoldersFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MoveFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
Labels: bug

#1632 Make PermissionUtils injectable
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
Labels: enhancement

#1633 Fix snackbar being displayed too soon with Storage Permission
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
Labels: bug

#1631 Hide Thread `emptyView` sooner so it doesn't blink
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug

#1635 Only display Tablet mode if `smallerWidth > 600dp` && `currentWidth > 840dp`
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: bug

#1638 Clean code
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Body.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsViewModel.kt
  app/src/main/res/layout/item_attachment.xml
  app/src/main/res/values-fr/strings.xml
Labels: optimization

#1637 Add missing `enableOnBackInvokedCallback` in Manifest
  app/src/main/AndroidManifest.xml
Labels: optimization

#1639 Clean code
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/DraftController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiEngineChoiceFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageAiManager.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncConfigureFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/AttachmentMimeTypeUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
  app/src/main/res/layout/fragment_search.xml
Labels: optimization

#1640 Add Avatar easterEgg
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/AccountFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/ConfettiUtils.kt
  app/src/main/res/values/colors.xml
Labels: feature

#1521 Tablet mode
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/LaunchActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/NoAnimSlidingPaneLayout.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPromptFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/RealmChangesBinding.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/res/drawable/ic_navigation_default.xml
  app/src/main/res/layout/fragment_ai_proposition.xml
  app/src/main/res/layout/fragment_invalid_password.xml
  app/src/main/res/layout/fragment_menu_drawer.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_thread.xml
  app/src/main/res/layout/fragment_thread_list.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-sw600dp-w840dp/constants.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/constants.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: feature

#1627 Basic calendar design
  app/src/main/java/com/infomaniak/mail/data/models/calendar/Attendee.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/AttendanceAvatarView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/ManyAvatarsView.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/color/button_calendar_participation_stroke_color.xml
  app/src/main/res/drawable/checkable_button_ripple_drawable.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_calendar_infomaniak.xml
  app/src/main/res/drawable/ic_calendar_maybe.xml
  app/src/main/res/drawable/ic_calendar_no.xml
  app/src/main/res/drawable/ic_calendar_participants_chevron.xml
  app/src/main/res/drawable/ic_chevron_up.xml
  app/src/main/res/drawable/ic_warning_big.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/view_attendance_avatar.xml
  app/src/main/res/layout/view_calendar_event_banner.xml
  app/src/main/res/layout/view_many_avatars.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: feature

#1643 Display Sync bottomSheet at 1st boot (instead of 5th boot)
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
Labels: enhancement

#1645 Clean Avatar code
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
  app/src/main/res/layout/cardview_thread_item.xml
Labels: optimization

#1649 Fix wrong Avatar displayed for Drafts
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: bug

#1647 Click on Avatar now opens MultiSelection
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: feature

#1655 Don't select Thread if we are just opening 1 Draft
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
Labels: bug

#1653 Use correct image loader for user's avatar
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: bug

#1652 Display Sync bottomSheet at 2nd boot (instead of 1st boot)
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: enhancement

#1651 Add attendees bottom sheet to calendar UI
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/AttendeesAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/AttendeesBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/utils/UiUtils.kt
  app/src/main/java/com/infomaniak/mail/views/BottomSheetScaffoldingView.kt
  app/src/main/res/layout/bottom_sheet_attendees.xml
  app/src/main/res/layout/item_attendee_avatar_name_email.xml
  app/src/main/res/layout/view_avatar_name_email.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
Labels: feature

#1658 Some minor UI updates according to new specs
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/CalendarEventBannerView.kt
  app/src/main/res/layout/view_calendar_event_banner.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1659 Fix snackbar blinking because of "Email sending in progress"
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
Labels: bug

#1654 Delete Draft when one of its Attachment cannot be uploaded
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: optimization

#1664 New calendar UI specs
  app/src/main/java/com/infomaniak/mail/ui/main/thread/calendar/ManyAvatarsView.kt
  app/src/main/res/layout/view_calendar_event_banner.xml
  app/src/main/res/layout/view_many_avatars.xml
Labels: enhancement, quick

#1660 Expose similar `safeNavigate` method in ThreadFragment as other fragments have
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#1668 Improve CI
  .github/workflows/android.yml
Labels: enhancement

#1673 Fix potential NPE
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menu/MenuDrawerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/AiPropositionFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
Labels: bug

#1676 Inject snackBarManager instead of passing callbacks everywhere and referencing the view model
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/ContextualMenuAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/EmailContextualMenuAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/LinkContextualMenuAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/PhoneContextualMenuAlertDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/SnackbarManager.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedContactBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/AttachmentActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncAutoConfigViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: enhancement

#1669 Sort API Routes code
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
Labels: optimization, quick

#1671 Invert `setDrawerLockMode()` parameter
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
Labels: optimization, quick

#1674 Permissions On boarding
  .idea/navEditor.xml
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/onboarding/PermissionsOnboardingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/onboarding/PermissionsOnboardingPagerFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/onboarding/PermissionsPagerAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/Extensions.kt
  app/src/main/java/com/infomaniak/mail/utils/PermissionUtils.kt
  app/src/main/res/drawable-night/illustration_onboarding_contacts.xml
  app/src/main/res/drawable-night/illustration_onboarding_contacts_blue.xml
  app/src/main/res/drawable-night/illustration_onboarding_contacts_material.xml
  app/src/main/res/drawable-night/illustration_onboarding_notifications.xml
  app/src/main/res/drawable-night/illustration_onboarding_notifications_blue.xml
  app/src/main/res/drawable-night/illustration_onboarding_notifications_material.xml
  app/src/main/res/drawable/illustration_onboarding_contacts.xml
  app/src/main/res/drawable/illustration_onboarding_contacts_blue.xml
  app/src/main/res/drawable/illustration_onboarding_contacts_material.xml
  app/src/main/res/drawable/illustration_onboarding_notifications.xml
  app/src/main/res/drawable/illustration_onboarding_notifications_blue.xml
  app/src/main/res/drawable/illustration_onboarding_notifications_material.xml
  app/src/main/res/layout/fragment_permissions_onboarding.xml
  app/src/main/res/layout/fragment_permissions_onboarding_pager.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature
