Repository Infomaniak/android-kMail, pull requests merged in 2025-05, with the labels that each got.

#2342 feat(Api35): Handle edge to edge in settings
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/SimpleSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/res/layout/view_simple_setting.xml
Labels: enhancement

#2350 fix: Revert "fix: Clean view holder in ThreadFragment when view is recycled to avoid crashes (#2330)"
  app/src/main/java/com/infomaniak/mail/ui/main/thread/AttachmentAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/DetailedRecipientAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/AttachmentDetailsView.kt
Labels: bug

#2354 perf: Do not call recomputeTwinFoldersThreadsDependantProperties when nothing has changed
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: optimization

#2355 feat: Paylock share email
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/MyKSuiteNavUtils.kt
Labels: enhancement

#2356 feat: Sdk 35 permissions
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/onboarding/PermissionsOnboardingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/onboarding/PermissionsOnboardingPagerFragment.kt
  app/src/main/res/layout/fragment_permissions_onboarding.xml
Labels: feature

#2357 feat(Sdk 25): QuickActionsBar
  app/src/main/java/com/infomaniak/mail/views/BottomQuickActionBarView.kt
Labels: enhancement

#2358 chore: Bump playServices library
  app/build.gradle
  gradle/libs.versions.toml
Labels: enhancement

#2347 fix: Add missing folder name tags in search results
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/ThreadResult.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
Labels: bug, enhancement

#2353 feat: Display messages coming from the snooze folder as such in the search
  app/src/main/java/com/infomaniak/mail/ui/main/search/NamedFolder.kt
  app/src/main/java/com/infomaniak/mail/utils/SearchUtils.kt
Labels: enhancement

#2360 chore: Update app logo icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_monochrome.xml
  app/src/main/res/drawable/ic_logo_notification.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement

#2364 fix(Api35): Fix sync activity for api 25
  app/src/main/java/com/infomaniak/mail/ui/login/IntroFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/login/LoginFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/onboarding/PermissionsOnboardingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/sync/SyncOnboardingFragment.kt
  app/src/main/res/layout/fragment_intro.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_permissions_onboarding.xml
  app/src/main/res/layout/fragment_sync_onboarding.xml
Labels: enhancement

#2373 fix: Keep network availability always up to date
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadProgressDialog.kt
Labels: bug

#2380 chore(EditorAction): Remove oxbow code "clock action"
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/res/layout/fragment_new_message.xml
Labels: enhancement
