Repository Infomaniak/android-kMail, pull requests merged in 2025-04, with the labels that each got.

#2299 fix: Fix the double navigation to MyKSuiteUpgradeBottomSheet
  app/src/main/java/com/infomaniak/mail/utils/MyKSuiteNavUtils.kt
Labels: bug

#2280 feat: Unsnooze messages and threads on the api when they receive a new message
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Snoozable.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
Labels: enhancement, feature

#2289 refactor: Display snackbars directly from viewmodel so it's centralized for each calling place
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement, quick

#2291 refactor: Remove unnecessary intermediate method that split logic in another file
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: enhancement, quick

#2290 feat: Add snooze actions to the thread bottom sheet
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/SnoozeBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/res/drawable/ic_alarm_clock.xml
  app/src/main/res/drawable/ic_circle_cross.xml
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
  app/src/main/res/layout/bottom_sheet_multi_select.xml
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
  app/src/main/res/layout/item_bottom_sheet_action.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2292 feat: Add snooze api calls success snackbars
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, quick

#2302 feat: Add snooze actions in multiselect bottom sheet
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/res/layout/bottom_sheet_multi_select.xml
Labels: feature

#2306 feat: Directly access snoozeUuid returned by the api instead of parsing snooze action
  app/src/main/java/com/infomaniak/mail/data/api/SnoozeUuidSerializer.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: enhancement

#2308 feat: Hide snooze actions in the thread header like the webmail does when not in snooze folder
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageAlertView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/res/layout/view_message_alert.xml
Labels: enhancement

#2311 refactor: Expose a `isSeen` property for a Thread instead of accessing `unseenMessagesCount` everytime
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
Labels: enhancement, quick

#2316 fix: Avoid realm migration crash when setting originalDate or reading snoozeAction
  app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
Labels: bug

#2317 feat: Remove the snooze status of an "unsnoozed" thread when reading it from any folder
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/MessageController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: feature

#2318 feat: Adapt text between confirm/modify depending on the type of snooze action
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForScheduledDraftDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForSnoozeDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#2320 feat: Drop db and reboot the app when realm migration failed
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
Labels: bug, enhancement

#2324 feat: Know if the snooze feature is available in current state with a single function
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: enhancement, quick

#2325 refactor: Remove unnecessary currentClassName
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: enhancement, quick

#2326 refactor: Extract SwipeAction enum to its own file
  app/src/main/java/com/infomaniak/mail/data/LocalSettings.kt
  app/src/main/java/com/infomaniak/mail/data/models/SwipeAction.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSettingsFragment.kt
Labels: enhancement, quick

#2328 fix: Use the correct wording when modifying the scheduled date of a draft
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement, quick

#2336 fix: Fix thread ordering
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: bug

#2333 refactor: Extract swipe action performing logic to its own file to reduce cognitive complexity
  app/src/main/java/com/infomaniak/mail/ui/main/folder/PerformSwipeActionManager.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: enhancement

#2337 feat: Refactor list of schedules and add missing matomo
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/SelectScheduleOptionBottomSheet.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/SnoozeBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
Labels: enhancement

#2338 fix: Unsnoozed date display when device's date is in the past
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListDateDisplay.kt
Labels: bug, quick

#2339 feat: Display and translate snooze api errors
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/models/snooze/BatchSnoozeResponse.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
