Repository Infomaniak/android-kMail, pull requests merged in 2025-06, with the labels that each got.

#2376 refactor: Remove "reassign" methods and use single centralized flows to handle message logic
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadState.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: enhancement

#2361 feat(Api35): Manage cutout in main activity
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/menuDrawer/SimpleSettingView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/appearance/swipe/SwipeActionsSelectionSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/WindowInsetsExt.kt
  app/src/main/java/com/infomaniak/mail/views/BottomQuickActionBarView.kt
  app/src/main/res/layout/fragment_swipe_actions_selection_setting.xml
  app/src/main/res/layout/fragment_thread_list.xml
Labels: enhancement

#2405 fix: Prevent crashes when switching users and trying to access values on a closed realm
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
Labels: bug

#2409 fix: When fetching more than one search page, add new page to existing threads
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug

#2427 fix: Return Result.success() inside DraftActionsWorker
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
Labels: bug

#2438 feat(Encryption-04): Add unencryptable recipients with encryptionButtonView
  app/src/main/java/com/infomaniak/mail/data/models/calendar/Attendee.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageEditorManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageRecipientFieldsManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionLockButtonView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionViewModel.kt
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/layout/view_encryption_lock_button.xml
  app/src/main/res/values/attrs.xml
Labels: feature

#2439 feat(Encryption-05): Encryptable actions bottomsheet
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionActionsBottomSheet.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
  app/src/main/res/drawable/ic_lock_password_field.xml
  app/src/main/res/layout/bottom_sheet_encryption_actions.xml
  app/src/main/res/navigation/new_message_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature
