Repository Infomaniak/android-kMail, pull requests merged in 2025-03, with the labels that each got.

#2211 feat(Matomo): Add tracker for block user dialog events
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/JunkBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/UserToBlockAdapter.kt
Labels: feature, quick

#2210 feat: Matomo my kSuite
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/MyKSuiteNavUtils.kt
Labels: feature, quick

#2231 fix: Revert "refactor: Tidy up `createNewThread()` (#2228)"
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
Labels: bug

#2218 feat: Compute snooze state in thread
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/SnoozeState.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: enhancement

#2221 feat: Filter snooze in folders
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/CustomRefreshStrategies.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshStrategies.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
Labels: enhancement

#2227 feat(MyKSuite): Stop fetching myKSuite data if user doesn't have a my kSuite offer
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxInfo/MailboxController.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/MykSuiteViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingsFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/LogoutUser.kt
  app/src/main/java/com/infomaniak/mail/utils/MyKSuiteDataUtils.kt
Labels: enhancement

#2222 feat: Introduce custom logic to handle deleted uids in the case of the snooze folder
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/CustomRefreshStrategies.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ImpactedFolders.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshStrategies.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
Labels: enhancement

#2238 feat: Do not log NameNotFoundException to sentry when saving to kDrive
  app/src/main/java/com/infomaniak/mail/utils/SaveOnKDriveUtils.kt
Labels: enhancement

#2243 feat: First snoozed thread UI
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListDateDisplay.kt
  app/src/main/res/drawable/ic_alarm_clock_thick.xml
  app/src/main/res/drawable/ic_editor_clock_small.xml
  app/src/main/res/drawable/ic_editor_clock_thick.xml
  app/src/main/res/drawable/ic_scheduled_messages.xml
  app/src/main/res/layout/cardview_thread_item.xml
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#2244 feat: Also recompute duplicated threads when snooze message is added/updated/deleted
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: enhancement

#2249 chore: Update alarm clock and clock icons with the correct stroke width versions
  app/src/main/res/drawable/ic_alarm_clock_thick.xml
  app/src/main/res/drawable/ic_editor_clock_thick.xml
Labels: quick

#2255 chore: Clean icons
  app/src/main/res/drawable/ic_alarm_clock_thick.xml
  app/src/main/res/drawable/ic_editor_clock_thick.xml
Labels: enhancement, quick

#2258 fix: Scheduled message's sorting order
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
Labels: bug, quick

#2259 refactor: Simplify and make code more readable
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/DefaultRefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/InboxRefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/RefreshStrategy.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/SnoozeRefreshStrategy.kt
Labels: enhancement

#2260 refactor: Turn refresh strategy and folder sort getter methods into property methods
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ThreadController.kt
  app/src/main/java/com/infomaniak/mail/data/models/Folder.kt
Labels: enhancement

#2271 fix: Display snoozed threads as such in the search
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: bug, enhancement

#2274 fix: Define displayDate in realm so we can query on it
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmMigrations.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
Labels: bug

#2191 chore: Replace DragDropSwipeRecyclerView dependency with our own fork
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListMultiSelection.kt
  app/src/main/java/com/infomaniak/mail/ui/main/search/SearchFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/Extensions.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_thread_list.xml
  gradle/libs.versions.toml
Labels: enhancement

#2285 fix: Add missing navargs definition that, only sometimes, prevents build
  app/src/main/res/navigation/main_navigation.xml
Labels: bug, quick

#2286 fix: Fix navigationBar color in dashboardFragment
  app/src/main/java/com/infomaniak/mail/ui/main/settings/KSuiteDashboardFragment.kt
Labels: bug

#2288 refactor: Don't make api call outside of the repository
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExt.kt
Labels: quick
