Repository Infomaniak/android-kMail, pull requests merged in 2025-09, with the labels that each got.

#2573 feat(EncryptionReply): Auto encrypt replies to an encrypted message
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: enhancement

#2571 feat: Encryption discovery bottomsheet
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionDiscoveryBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionUtils.kt
  app/src/main/res/drawable-night/illu_encrypted_mail.xml
  app/src/main/res/drawable/illu_encrypted_mail.xml
  app/src/main/res/layout/bottom_sheet_encryption_discovery.xml
  app/src/main/res/layout/bottom_sheet_information.xml
  app/src/main/res/navigation/new_message_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#2596 chore: Clean useless matrices
  .github/workflows/android.yml
  .github/workflows/ui-tests.yml
Labels: enhancement, quick

#2599 fix: Wrap MailBottomSheetScaffoldComposeView into a FrameLayout to avoid animation crash
  app/src/main/java/com/infomaniak/mail/ui/components/views/MailBottomSheetScaffoldComposeView.kt
Labels: bug

#2617 fix: Add query param to receive emoji_reaction field from the search
  app/src/main/java/com/infomaniak/mail/data/api/ApiRoutes.kt
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/refreshStrategies/ThreadRecomputations.kt
Labels: bug, quick
