Repository Infomaniak/android-kMail, pull requests merged in 2025-02, with the labels that each got.

#2153 refactor: Regroup swipe refresh logic that goes together
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
Labels: quick

#2155 fix: Revert Realm breadcrumbs
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/utils/SentryRealmLogger.kt
Labels: quick

#2156 refactor: Avoid duplicating values when defining what folders need to refresh together
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: enhancement, quick

#2164 feat: Add missing schedule date format in ThreadListFragment
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListDateDisplay.kt
  app/src/main/res/layout/cardview_thread_item.xml
Labels: feature

#2165 fix: Fix hardcoded 24 hour format
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/ReplyForwardFooterManager.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/PrintHeaderUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/date/DateFormatUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/date/MailDateFormatUtils.kt
Labels: bug, enhancement

#2168 feat: Display year date when the date is on another year
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/utils/date/DateFormatUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/date/MailDateFormatUtils.kt
Labels: enhancement, quick

#2169 refactor: Hide schedule time picker cursor and remove unused hint space
  app/src/main/res/layout/dialog_select_date_and_time_for_scheduled_draft.xml
Labels: quick

#2171 refactor: Remove unused values in SelectDateAndTimeForScheduledDraftDialog
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForScheduledDraftDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/res/layout/dialog_select_date_and_time_for_scheduled_draft.xml
Labels: enhancement, quick

#2166 fix: Add missing ActionItemView_description styleable
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ActionItemView.kt
  app/src/main/res/values/attrs.xml
Labels: enhancement, quick

#2179 chore: Better align expeditor name, schedule date, and icons
  app/src/main/res/drawable/ic_scheduled_messages_small.xml
  app/src/main/res/layout/item_message.xml
Labels: enhancement

#2180 fix: Default reply signatures ignored when set as "Identical to new messages" on the web
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: bug

#2182 fix: Wrong signature and reply action used due to case-sensitive emails
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
Labels: bug, quick

#2177 feat(MyKSuite-02): Block signature for free account
  app/src/main/java/com/infomaniak/mail/ui/main/settings/SettingRadioButtonView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/settings/mailbox/SignatureSettingFragment.kt
  app/src/main/java/com/infomaniak/mail/utils/MyKSuiteUiUtils.kt
  app/src/main/res/layout/view_setting_radio_button.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: feature

#2174 feat: Make time picker dialog reusable
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/alertDialogs/SelectDateAndTimeForScheduledDraftDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/bottomSheetDialogs/ScheduleSendBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/res/layout/dialog_select_date_and_time.xml
Labels: enhancement

#2200 fix: Fix notification worker
  app/src/main/java/com/infomaniak/mail/utils/NotificationUtils.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/standard/java/com/infomaniak/mail/firebase/ProcessMessageNotificationsWorker.kt
Labels: bug, quick

#2190 fix: Wrong avatar after user name change
  app/src/main/java/com/infomaniak/mail/ui/main/AvatarNameEmailView.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/user/SwitchUserAdapter.kt
  app/src/main/java/com/infomaniak/mail/views/AvatarView.kt
Labels: bug

#2203 refactor: Decouple impacted folder ids computation in thread algo deleted uids handling
  app/src/main/java/com/infomaniak/mail/data/cache/mailboxContent/RefreshController.kt
Labels: enhancement

#2088 feat: Save thread on kDrive
  .idea/navEditor.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/infomaniak/mail/MatomoMail.kt
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/TwoPaneFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadAttachmentProgressDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadMessagesProgressDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadMessagesViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/DownloadProgressDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MailActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MessageActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/MultiSelectBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/actions/ThreadActionsBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/LocalStorageUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SaveOnKDriveUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/Utils.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/AttachmentExtensions.kt
  app/src/main/java/com/infomaniak/mail/utils/extensions/NavigationExtensions.kt
  app/src/main/res/layout/bottom_sheet_actions_menu.xml
  app/src/main/res/layout/bottom_sheet_multi_select.xml
  app/src/main/res/layout/dialog_download_progress.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/exposed_files_path.xml
Labels: feature

#2208 chore(Sentry): Avoid logging NetworkException
  app/src/main/java/com/infomaniak/mail/MainApplication.kt
  app/src/main/java/com/infomaniak/mail/utils/MyKSuiteDataUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/SharedUtils.kt
Labels: enhancement, quick
