Repository Infomaniak/android-kMail, pull requests merged in 2025-07, with the labels that each got.

#2460 feat(Encryption-09): Clean encryption lock button view and add delay to loader
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionLockButtonView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
  app/src/main/res/layout/fragment_new_message.xml
  app/src/main/res/values/attrs.xml
Labels: enhancement, feature

#2464 feat(Encryption-10): Use mediator to update encryption status
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/NewMessageViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionLockButtonView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionViewModel.kt
Labels: enhancement, feature

#2465 feat(Encryption-11): Various fixes
  app/src/main/java/com/infomaniak/mail/data/cache/userInfo/MergedContactController.kt
  app/src/main/java/com/infomaniak/mail/data/models/calendar/Attendee.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Correspondent.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/MergedContact.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactChipAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionActionsBottomSheet.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionLockButtonView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionPasswordFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionStatus.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionViewModel.kt
  app/src/main/res/color/encryption_on_primary_color.xml
  app/src/main/res/color/encryption_primary_color.xml
  app/src/main/res/layout/fragment_encryption_password.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, feature

#2467 feat(Encryption-12): Better recipients chips
  app/src/main/java/com/infomaniak/mail/ui/newMessage/ContactChipAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/RecipientFieldView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptableView.kt
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionMessageManager.kt
Labels: enhancement, feature

#2470 feat: Create a compose mail bottom sheet scaffold to contain future compose code
  app/build.gradle
  app/src/main/java/com/infomaniak/mail/ui/components/MailBottomSheetScaffold.kt
  app/src/main/java/com/infomaniak/mail/ui/components/views/MailBottomSheetScaffoldComposeView.kt
  app/src/main/res/layout/view_bottom_sheet_scaffolding.xml
  app/src/main/res/layout/view_bottom_sheet_separator.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: enhancement

#2473 fix(EncryptionUi): Fix small Ui problems
  app/src/main/res/drawable/ic_lock_filled_big.xml
  app/src/main/res/layout/bottom_sheet_encryption_actions.xml
  app/src/main/res/layout/item_message.xml
Labels: bug

#2476 fix: Fix MessageAlertView default styling when no style is provided
  app/src/main/java/com/infomaniak/mail/ui/main/thread/MessageAlertView.kt
  app/src/main/res/layout/item_message.xml
  app/src/main/res/values/attrs.xml
Labels: bug

#2480 fix(EncryptionRegex): Fix bold argument
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionActionsBottomSheet.kt
Labels: bug, enhancement

#2482 feat(encryption): Use new Api `with` to get if the recipients should be displayed in the unencryptable bottomsheet
  app/src/main/java/com/infomaniak/mail/data/api/ApiRepository.kt
  app/src/main/java/com/infomaniak/mail/data/cache/RealmDatabase.kt
  app/src/main/java/com/infomaniak/mail/data/models/correspondent/Recipient.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
Labels: feature

#2483 feat: Encryption support more than 10 recipients in one check
  app/src/main/java/com/infomaniak/mail/ui/newMessage/encryption/EncryptionViewModel.kt
Labels: enhancement

#2407 feat: Translate emoji reaction errors
  app/src/main/java/com/infomaniak/mail/data/models/message/EmojiReactionNotAllowedReason.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/emojiPicker/EmojiPickerBottomSheetDialog.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: feature, quick

#2501 chore: Revert "fix: Force bottom sheet as fullscreen to fix issue of cropped bottom part of the emoji recyclerview"
  app/src/main/java/com/infomaniak/mail/ui/main/emojiPicker/EmojiPickerBottomSheetDialog.kt
Labels: quick

#2433 feat: Fake sent emojis locally
  EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/EmojiReactions.kt
  app/src/main/java/com/infomaniak/mail/ui/MainActivity.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/PrintMailFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/models/MessageUi.kt
  app/src/main/java/com/infomaniak/mail/workers/DraftsActionsWorker.kt
  app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt
Labels: feature

#2434 feat: Prevent sending emojis when not allowed
  app/src/main/java/com/infomaniak/mail/ui/MainViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/utils/EmojiReactionUtils.kt
  app/src/main/java/com/infomaniak/mail/utils/ErrorCode.kt
Labels: feature

#2435 feat: Hide reactions if not available
  EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/AddReactionChip.kt
  EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/EmojiReactions.kt
  EmojiComponents/src/main/java/com/infomaniak/emojicomponents/views/EmojiReactionsView.kt
  app/src/main/java/com/infomaniak/mail/data/models/message/Message.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadViewModel.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/models/MessageUi.kt
  app/src/test/java/com/infomaniak/mail/CalendarEventResponseTest.kt
Labels: feature

#2508 feat: Show a snackbar when clicking on an already used emoji
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: enhancement

#2514 fix: Fix scheduled thread display in search
  app/src/main/java/com/infomaniak/mail/data/models/thread/Thread.kt
  app/src/main/java/com/infomaniak/mail/ui/main/folder/ThreadListAdapter.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/ThreadFragment.kt
Labels: bug, enhancement

#2515 feat: Add missing view composition strategy in emoji reaction feature
  EmojiComponents/src/main/java/com/infomaniak/emojicomponents/views/EmojiReactionsView.kt
  EmojiComponents/src/main/res/values/attrs.xml
  app/src/main/java/com/infomaniak/mail/ui/components/MailBottomSheetScaffold.kt
  app/src/main/java/com/infomaniak/mail/ui/components/views/MailBottomSheetScaffoldComposeView.kt
  app/src/main/res/layout/item_message.xml
Labels: bug, enhancement

#2516 refactor: Remove useless lambda around compose state
  EmojiComponents/src/main/java/com/infomaniak/emojicomponents/components/EmojiReactionDetails.kt
  app/src/main/java/com/infomaniak/mail/ui/main/thread/EmojiReactionDetailsBottomSheet.kt
Labels: quick
